cucumber/aruba

.travis.yml

The guys @ TravisCI set up a new build infrastructure which supports "faster" build by using `docker`
See http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/ for more information.

Use new travis build infrastructure

---

lib/aruba/api.rb
lib/aruba/matchers/file.rb
lib/aruba/matchers/mode.rb
spec/aruba/api_spec.rb
spec/spec_helper.rb
spec/support/shared_examples/directory.rb
spec/support/shared_examples/file.rb

@jarl-dk 
When creating a fixture using `touch_file` it can be quite handy to set the timestamp to a fixed time. This PR makes this possible by passing through options to `FileUtils`.
This
```ruby
touch_file 'file.txt', mtime: Time.parse('2014-01-01 10:00:00')
```
works like that
```bash
#/bin/bash
touch -d '2014-01-01 10:00:00' file.txt
```
This also speeds up tests, because you do not need to do something nasty like this:
```ruby
touch_file 'file.1.txt'
sleep 1
touch_file 'file2.txt'
```

Support for setting mtime when using #touch_file

---

lib/aruba/api.rb
lib/aruba/cucumber.rb
lib/aruba/cucumber/hooks.rb
lib/aruba/reporting.rb
spec/aruba/api_spec.rb
spec/spec_helper.rb

Every method which works on a file is named `*_file`. Every method which works on a directory is named `*_dir`. While file is fully written, directory is abbreviated. This PR changes this. Now all methods are fully written.

Rename *_dir to *_directory

---

README.md
lib/aruba/api.rb
lib/aruba/matchers/file.rb
lib/aruba/matchers/mode.rb
spec/aruba/api_spec.rb

This PR adds the basics to support fixtures in `aruba`. Also see  #219.
Things to discuss:
I used `OpenStruct` here to make both paths of a fixture available: The relative one which is used to find a fixture and the absolute one, which can be used by a `consumer` of the api like `copy_file`. I can replace this by a `Hash` if this is preferred. Though `OpenStruct` is part of `ruby core distribution`.
I like the `relative_path_from`-functionality of `Pathname`. It makes the intention of the author clear and is quite easy to use to build relative paths.
It does not have a special meaning in ruby so far - besides percent classes which are not followed by `/`.
I use "my" preferred order here, but I'm open to change it.
I will refactor the "commits" after all things above are discussed to make …

Add fixtures to aruba

---

features/file_system_commands.feature
features/interactive.feature
lib/aruba/cucumber.rb

I often use an `init`-command to create some files. In my steps I try to make it obvious that the file should not exist. This PR adds new cucumber steps which makes the intent very clear and does not fail if I file/directory does not exist. This PR also includes a small refactoring - hope this is ok.
New steps
* Make sure file does not exist
* Make sure directory does not exist
Cleanup step
* Make directory step look the same like file step
I'm very well aware of the `I remove file/directory "xz.txt"`-step. But I think the intention is very different.

Make sure a file/directory does not exist + Cleanup named file/directory steps

---

.gitignore
.yardopts
lib/aruba/matchers/mode.rb
lib/aruba/matchers/rspec_matcher_include_regexp.rb

I think the `have_permissions`-matchers is usable for other people as well. I think we should remove the `@private`-flag.
```ruby
describe 'my feature' do
it { expect('file.txt').to have_permissions(0700) }
end
```
I also added a configuration file for `yardoc` and the directory which is generated by `yardoc` during documentation generation is ignored now.
@mattwynne @jarl-dk Suggestions?

Make matcher have_permisions public and add documentation

---

lib/aruba/matchers/file.rb
spec/aruba/api_spec.rb
spec/aruba/matchers/file_spec.rb
spec/support/shared_contexts/aruba.rb

I added a matcher to match string to file content. This might be useful for aruba internals as well, but is itended to be part of the public API.
This PR is based on a refactoring done in #237, that's why there are some more commits added here. I will rebase this PR.

Added matcher for file content

---

README.md
lib/aruba/rspec.rb

Make it easier for others to integrate `aruba` with rspec.
BTW and as a reminder for me in the future:
This https://github.com/jnicklas/capybara/blob/master/lib/capybara/rspec.rb is a good example.
We may need to discuss the `type`. I'm open for suggestions. What about `type: :aruba` or `type: :cli`?

Add rspec integrator

---

lib/aruba/api.rb
lib/aruba/cucumber.rb
lib/aruba/errors.rb
lib/aruba/matchers/directory.rb
lib/aruba/matchers/file.rb
lib/aruba/matchers/path.rb
lib/aruba/matchers/rspec_matcher_include_regexp.rb
spec/aruba/api_spec.rb
spec/aruba/matchers/directory_spec.rb
spec/aruba/matchers/file_spec.rb
spec/aruba/matchers/path_spec.rb
spec/support/shared_examples/directory.rb
spec/support/shared_examples/file.rb

When we have `file?` and `directory?` in place, I see no need to have `remove_file`, `remove_directory`   and `touch_file` anymore.
Be stating `_file` and `_directory` in the name we mix a test and an action. I think users should use the `file?` and `directory?`-methods for tests and `remove` and `touch` for actions.
I changed the implementation of the given methods to work both on files and directories. All relevant changes are from the 2nd of May.
This PR is based on #237.

Remove _file/_directory in method names

---

.simplecov
.travis.yml
CONTRIBUTING.md
Gemfile
aruba.gemspec
doc/dependency_decisions.yml
script/bootstrap
script/test
spec/spec_helper.rb
spec/support/configs/rspec.rb

1. Remove ruby 1.9.3 from supported rubies
Ruby 1.9.3 is End of Life. I see no reason to officially support a ruby
version which does not get any bugfixes from core developers.
2. Add support for JRuby 2 and 2.1 mode
3. Debugging
`pry` seems to be the debugger-tool in the ruby-world. Together with byebug
(ruby 2 only) even code walking is possible. The stack_explorer plugin gives
you a nice access to the stack trace. The doc-plugin makes ruby doc available from within a pry session
4. License Finder
`aruba` seems be used widely. So extra care should be taken with licensing
issues. The [license_finder](https://github.com/pivotal/LicenseFinder) helps
you with that. It tracks license of all uses libraries. I whitelisted the MIT
and the BSD-licenses, I think there's no problem here. I …

Improve development environment

---

lib/aruba/api.rb
lib/aruba/cucumber.rb
spec/aruba/api_spec.rb
spec/support/helpers/reporting.rb

Follow up to #224.
@jarl-dk 
You changed the public API of `#absolute_path`. I think we should deprecate that API properly first. To make the switch easier for us I added the old implementation of `absolute_path` and left the new one to `expand_path`. What do you think?
To make it possible to use `expand_path` everywhere I removed the `prep_for_fs`-call, because otherwise we would have doubled the `tmp/aruba`-path in the expanded path.
Do you see any reason to keep the method as part of `aruba`. I mark it as deprecated.
I added single commits for the changes to make review easier. I will squash them after the review.
I also added a spec for the `absolute_path` as long as it is part of `aruba`. The deprecation warning is silenced.

use expand path everywhere

---

.simplecov
features/support/env.rb
features/support/simplecov_setup.rb
spec/aruba/spawn_process_spec.rb

simplecov is a wrapper on the built-in coverage library for Ruby 1.9+.  When running `rake spec` or `rake cucumber`, a coverage report will be output in coverage/index.html.  If you run both tasks or all tasks with `rake spec` within a close enough time window (I think 10 minutes) the results will all be merged so you can get coverage across both the specs and features.  If this PR is accepts, then I'll add another to use coveralls.io to publish the coverage reports to coveralls.io, but someone with admin access will have to setup the hooks on coveralls.io for that.  Additionally, the reports from simplecov are a confirmation that not all steps are being exercised, include the ones dealing with rvm.  I have a fix for that too that I can post in a later PR.

Use simplecov for coverage reports for specs and cucumber

---

.rubocop.yml
aruba.gemspec
lib/aruba/api.rb
lib/aruba/matchers/directory.rb
lib/aruba/matchers/file.rb
lib/aruba/matchers/path.rb
spec/aruba/api_spec.rb
spec/aruba/matchers/directory_spec.rb
spec/aruba/matchers/path_spec.rb

This reads content from
* directory
* file
And returns an array of content. Next step would be to use it "everywhere" in the code. `rubcop` complains if I use `ArgumentError` although that should be ok. For now I disabled the check.

Path Content

---

lib/aruba/processes/spawn_process.rb
spec/aruba/spawn_process_spec.rb

`Processes::SpawnProcess#stop` calls `Announcer::PutsAnnouncer#stderr` and `#stdout`, triggering [these](https://github.com/cucumber/aruba/blob/abd78e67237e5951bb3256d9235bfc6597db22c9/lib/aruba/announcer.rb#L137) [two](https://github.com/cucumber/aruba/blob/abd78e67237e5951bb3256d9235bfc6597db22c9/lib/aruba/announcer.rb#L142) deprecation warnings in third party projects that use Aruba.
This fixes the problem. :)

Do not trigger Announcer API deprecation warning

---

features/fixtures/empty-app/.gitignore
features/fixtures/empty-app/.rspec
features/fixtures/empty-app/README.md
features/fixtures/empty-app/Rakefile
features/fixtures/empty-app/bin/cli
features/fixtures/empty-app/cli-app.gemspec
features/fixtures/empty-app/lib/cli/app.rb
features/fixtures/empty-app/lib/cli/app/version.rb
features/fixtures/empty-app/script/console
features/fixtures/empty-app/spec/spec_helper.rb
features/integration/rspec/getting_started.feature
features/step_definitions/aruba_dev_steps.rb
features/steps/environment/home_variable.feature
lib/aruba/api/command.rb
lib/aruba/api/core.rb
lib/aruba/cucumber/hooks.rb
lib/aruba/rspec.rb
lib/aruba/version.rb

If someone does not run `setup_aruba` before `write_file` and all other `aruba`-methods, it fails with `Errno::ENOENT`.
This PR refactors the `expand_path`-method not to rely on the existence of the working directory.  Plus, a warning and some example were added about the correct use.

Fix problem if working directory does not exist

---

features/api/filesystem/disk_usage.feature
features/configuration/physical_block_size.feature
lib/aruba/api/filesystem.rb
lib/aruba/aruba_path.rb
lib/aruba/config.rb
lib/aruba/contracts/is_power_of_two.rb
lib/aruba/disk_usage_calculator.rb
lib/aruba/file_size.rb

This adds a method to report the disk usage for files and directories. It's different from `File.size`as this uses the amount of blocks really allocated on disk and reports a different value for `Sparse Files` (http://prefetch.net/blog/index.php/2009/07/05/creating-sparse-files-on-linux-hosts-with-dd/).

Add disk usage

---

lib/aruba/platforms/unix_platform.rb
lib/aruba/platforms/unix_which.rb
lib/aruba/platforms/windows_platform.rb
lib/aruba/platforms/windows_which.rb
lib/aruba/processes/spawn_process.rb

Unix and Windows need a separate logic to find executables in PATH. This splits up the original implementation and uses `Aruba.platform` to decide which implementation to use.

Split up which for Unix and Windows

---

aruba.gemspec
bin/aruba
features/cli/console.feature
features/configuration/console_history_file.feature
lib/aruba/api/command.rb
lib/aruba/cli.rb
lib/aruba/config.rb
lib/aruba/console.rb
lib/aruba/console/help.rb
lib/aruba/cucumber.rb
lib/aruba/platforms/unix_platform.rb
lib/aruba/processes/basic_process.rb

This adds a console to aruba which users can use as "sandbox". It uses `tmp/aruba` as temporary directory.

Add console support to aruba

---

lib/aruba/cucumber/command.rb

This PR replaces `exit_timeout` with `aruba.config.exit_timeout`.

Fix '"#exit_timeout" is deprecated' error

---

features/api/environment/delete_environment_variable.feature
features/api/environment/set_environment_variable.feature
features/configuration/command_runtime_environment.feature
lib/aruba/api/command.rb
lib/aruba/api/core.rb
lib/aruba/config.rb
lib/aruba/cucumber/hooks.rb
lib/aruba/platforms/unix_environment_variables.rb
lib/aruba/platforms/unix_platform.rb
lib/aruba/platforms/windows_environment_variables.rb
lib/aruba/platforms/windows_platform.rb
lib/aruba/rspec.rb
lib/aruba/runtime.rb

`ruby-stylus` sets `ENV['NODE_PATH']` but aruba's env ignores that. I hope to fix it one time in the future. This PR tracks the progress.

Refactor set/remove environment variables

---

features/api/command/run_simple.feature
features/configuration/activate_announcer_on_command_failure.feature
features/steps/command/run.feature
lib/aruba/api/command.rb
lib/aruba/config.rb

Happy New Year!
When testing some long-running flaky commands it can be quite difficult to understand what is causing a command to fail.
I think it could be useful to show the command's output if it failed unexpectedly.
This might be completely the wrong way of accomplishing that.
Wdyt in general of the idea?

Show output when command fails with "fail_on_error"

---

History.md
aruba.gemspec
lib/aruba/errors.rb
lib/aruba/event_bus.rb
lib/aruba/event_bus/name_resolver.rb
lib/aruba/runtime.rb
spec/event_bus/name_resolver_spec.rb
spec/event_bus_spec.rb
spec/spec_helper.rb
spec/support/configs/aruba.rb

Follow up to fedux-org/event-bus#6. This brings back code into `aruba` to make maintenance easier.

Re-integrate code of event-bus library

---

script/bootstrap

On dark backgrounds, black was unreadable.
In most cases, e[39;39m should correctly reset the fg and bg colors.

Correctly reset term colors (scripts)

---

lib/aruba/platforms/windows_environment_variables.rb
spec/aruba/platform/windows_environment_variables_spec.rb

WindowsEnvironmentVariables implemented `:delete` with 2 args instead of 1.
This was fixed and spec was added to it can be tested on Linux.
Failed only on AppVeyor (Windows).
Related issue: https://github.com/cucumber/aruba/issues/349
RSpec, locally.

Fix broken ENV.delete (on Windows)

---

lib/aruba/cucumber/file.rb

Fixes the "the following files should exist:" cucumber step table handling so it checks all files supplied.
I had started with a cucumber scenario in which it wasn't failing like I expected to. I added a header to the table that was using the "following files should exist" table and then it failed. However, the documentation and tests for that rule i.e. https://github.com/cucumber/aruba/blob/master/features/cli/init.feature#L11 have without a header.
There are existing tests for this, however, they weren't actually testing it correctly. Now they do.

ignore table headers on 'following files exist:' step

---

lib/aruba/processes/basic_process.rb
lib/aruba/processes/spawn_process.rb
spec/aruba/processes/basic_process_spec.rb
spec/aruba/spawn_process_spec.rb

An old, undefined variable (`cmd`) was left over after refactoring. It was replaced with the right one (`commandline`).
Also, a spec was added to force the code to fail on Unix.
This caused failures on AppVeyor, because the exception handler crashed.
This failed only on Windows because the PATH traversing didn't throw an error earlier.
Still, the error could've occurred on Unix if the program was in the PATH (so no exception there), and yet there was an error accessing a program's file (like if the file wasn't readable). 
Fixes failure on AppVeyor.
Locally, RSpec.
This probably can be simulated in Cucumber scenarios by having an unreadable binary file (e.g. using `chmod -r`)

Fix broken exception handler

---

features/api/filesystem/disk_usage.feature
lib/aruba/api/filesystem.rb
lib/aruba/aruba_path.rb
lib/aruba/config.rb
lib/aruba/platforms/determine_disk_usage.rb
spec/aruba/aruba_path_spec.rb

Implement `ArubaPath#blocks` by guessing when it's not available for a given filesystem.
NOTE: If the block size cannot be determined, a default of 4096 is used. (I'm aware this is different from the default of `Aruba.config.physical_block_size`, which has a default of 512 - I believe it should be 4096).
The formula is basically asking "how many blocks are needed to at least fit the file's size?".
A spec was added to test various edge values.
If `File::Stat.blocks` is nil, guessing is a better option than nothing.
Also, "disk usage" based on "blocks reported by stat()" is unreliable because of filesystem metadata and things like compression/deduplication (e.g. BTRFS).
So since disk usage is a "guess" at best anyway, I implemented this by calculating the blocks based on the file size. …

"Compatibly" reimplement disk_usage API and logic

---

.travis.yml
History.md
aruba.gemspec

This PR drops supported for unsupported rubies from 1.0.0 on.

Drop unsupported rubies

---

.travis.yml

Add ruby-2.4.0 and ruby-head to .traivs.yml.
The details and the motivation is same with https://github.com/cucumber/cucumber-ruby/pull/1087
Travis will test it.

Add Ruby 2.4.0 and ruby-head in .travis.yml.

---

features/testing_frameworks/cucumber/setup.feature
lib/aruba/cucumber/command.rb
lib/aruba/cucumber/hooks.rb
lib/aruba/platforms/windows_command_string.rb
spec/aruba/matchers/command_spec.rb

This pull request fixes #387 and makes aruba functional on Windows

Fix running commands on Windows (#387)

---

lib/aruba/platforms/command_monitor.rb

Some changes to get Aruba in a state that's happy to run when the `--enable-frozen-string-literal` flag is being used. 
I'm trying to get the RSpec test suite to a point where it can run with frozen string literals on MRI 2.4, and it makes use of Cucumber and Aruba, hence this patch (and another shortly for Cucumber as well).
The test suite for Aruba doesn't seem to be passing in its current state? So, my testing of this patch was done via running the Cucumber and rspec-core suites instead (which make use of Aruba). Hence, these patches may not be all the places where frozen string literals are being misused, but they're certainly the only places that crop up via either of the other test suites.
Depends if you consider supporting frozen string literals a feature or a bug. ¯\_(ツ)_/¯
As …

Improve frozen-string-literals compatibility.

---

script/test

Fixes script/test so its exit code is that of rake rather than of echo.
The Travis builds seem green, but if you look at the logs there are a lot of failed scenarios. It seems a lot of things are broken and actually failing the build is a first step to fixing them.

Actually fail the build if rake test fails

---

lib/aruba/api.rb
lib/aruba/runtime.rb
spec/aruba/api_spec.rb
spec/aruba/hooks_spec.rb
spec/aruba/processes/basic_process_spec.rb
spec/aruba/spawn_process_spec.rb
spec/event_bus/name_resolver_spec.rb
spec/event_bus_spec.rb

These changes make the RSpec specs run to completion.
These are some small fixes so RSpec doesn't abort prematurely:
* Load deprecated method module because it is still included and its methods are still tested (and sometimes used).
* Fix initialization of CommandMonitor; it always needs an announcer.
* Fix some left-over instances of the moved `#run` method.
* Load `spec_helper` in all spec files. This is mainly important when checking spec failures by running individual files.
This is a small part of #434 that hopefully can be merged more quickly so there is a basis for making the final fixes to the specs and then fixing the cucumber scenarios.

Make rspec run all specs

---

lib/aruba/api/deprecated.rb
lib/aruba/basic_configuration.rb
lib/aruba/config.rb
lib/aruba/console.rb
lib/aruba/event_bus/name_resolver.rb
lib/aruba/platforms/command_monitor.rb
lib/aruba/platforms/unix_environment_variables.rb
lib/aruba/platforms/unix_which.rb
lib/aruba/platforms/windows_which.rb
lib/aruba/processes/spawn_process.rb
spec/event_bus_spec.rb

This PR avoids all of the currently output RuboCop warnings.

RuboCop Lint/UnneededDisable warnings heeded

---

lib/aruba/api/core.rb
lib/aruba/cucumber/hooks.rb
lib/aruba/rspec.rb
spec/aruba/api_spec.rb
spec/aruba/rspec_spec.rb
spec/support/shared_contexts/aruba.rb

Improve handling of environment. In particular, makes `ENV['HOME']` have a correct and safe value.
~~This PR depends on #441 so needs to be rebased after that PR has been merged.~~
The main purpose is to make all the current specs pass. It does this by changing the environment setup in the specs, so that:
* HOME and PATH are set early enough so that all specs run with the set values. This also ensures no leaking of files outside of the build directory.
* Where the Aruba runtime is the object under test, it uses the test object when expanding paths.
This change also fixes the `#cd` method to not clear the entire environment inside the block.
After this PR has been merged we can revisit #434 and concentrate on the cucumber scenarios there.

Fix environment handling

---

Gemfile

Downgrade `license_finder` to make the build succeed.
The gem uses the new "Safe Navigation Operator" which was introduced in
C-Ruby 2.3. This make the build fail: https://travis-ci.org/cucumber/aruba/jobs/252903532.

Use old version of license_finder for old rubies

---

features/README.md

Issue: When following the _Your First Tests_, there's no explicit instruction to run `bundle install`
```
Could not find gem 'aruba (~> 1.0.0.pre.alpha.1)' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.
```
Solution: add that, and mention it in step 1.
See #453

[docs] Your first Tests tutorial: add install step

---

features/README.md

This fixes based on [this](https://github.com/cucumber/aruba/issues/453#issuecomment-315591584) comment by @mvz. Additionally it does some minor refactorings to the README
* Fix example for first-timers (https://github.com/cucumber/aruba/issues/453#issuecomment-315591584)
* Move usage of `aruba` with existing projects to the end to make the README more accessible for first timers

[ci skip] Refactor documentation

---

README.md
features/README.md

This fixes some sections for aruba developer docs.
Make docs easier to access.

Fix docs for developers

---

features/04_aruba_api/filesystem/use_fixtures.feature

This PR improves the documentation about using our fixtures API.
* Fix false positive feature tests - they creating the wrong file and succeed although they should have failed
* Add example about how to use fixtures along with commands
I've got an ongoing valuable discussion with @remy about the usage of fixtures. It turned out, that our docs are wrong at some places and additionally a good example was missing to clarify the use of fixtures with commands.

Improve docs to use our fixtures

---

features/01_getting_started_with_aruba/cleanup_working_directory.feature

This fixes the wording of the `@no-clobber`-tag in our docs.

Clearify use of no clobber in cucumber

---

features/02_configure_aruba/root_directory.feature
features/03_testing_frameworks/cucumber/setup_aruba_for_cucumber.feature
features/03_testing_frameworks/cucumber/steps/command/check_output_of_command.feature
features/03_testing_frameworks/cucumber/steps/command/check_stderr_of_command.feature
features/04_aruba_api/core/expand_path.feature
features/04_aruba_api/text/sanitize_text.feature
features/04_aruba_api/text/unescape_text.feature
lib/aruba/api/text.rb
lib/aruba/config.rb
lib/aruba/platforms/command_monitor.rb

Fix CI errors.
This PR fixes errors on CI to make the build pass again.
Make the build pass again.

Fix bugs in features/aruba

---

README.md

This is a follow up to #458. 
As far as I remember we had several users who were not familiar with cucumber and ruby. This PR points them to the documentation of all supported testing frameworks to make it easier for them to find the information they need.
We want to reduce the burden for users to use "aruba" and "cucumber".

Add links to documentation about various testing frameworks

---

Gemfile

Remove gems which are only required for unsupported platforms like Rubinius.

Remove gems for unsupported rubinius platform

---

.travis.yml

Restrict branches to run Travis.
For example, below case.
2 builds (PR and branch push) on Travis are running.
https://github.com/cucumber/aruba/pull/465
When sending pull-request from cucumber/aruba repository's branch,
prevent 2 builds to run.
Saving the resource.
That affects Travis's running time.
If the time becomes shorten, contributors are happy.
When sending pull-request from `cucumber/aruba`'s branch, that is tested.

Restrict branches to run Travis.

---

README.md

Move Build Status Badge to top of the README page.
Right now build status is in the bottom of the `README.md`.
This style has been seen by https://github.com/rails/rails
However, other projects in cucumber have the build status on the top of `README.md`.
such as
https://github.com/cucumber/cucumber-ruby/blob/master/README.md
https://github.com/junaruga/cucumber-ruby-core/blob/master/README.md
https://github.com/cucumber/gherkin-ruby/blob/master/README.md
This style's merit is that people can see the status easily without scroll down.
I think that this style promotes contribution to pass tests.
You can see modified README here.
https://github.com/junaruga/aruba/blob/feature/build-status-badge-on-top/README.md
By the way,
https://ci.appveyor.com/project/cucumberbdd/aruba/branch/still
> …

Move Build Status Badge to top of the README page.

---

appveyor.yml

Add "still" branch in Appveryor (CI for Windows environment).
"master" and "still" branches are used for production.
But "still" is not set in appveryor.yml
Seeing past "git log", it is just forgot to add it.
This prevents Appveryor to run 2 time per PR for pull-requeset to still branch.
This saves CI resource.
When sending pull-request to still branch, we will know it is correct.
- [] Refactoring (cleanup of codebase withouth changing any existing functionality)

Add "still" branch in Appveryor (CI for Windows environment).

---

README.md

Fix a typo for README appver badge image URL pending text.
This fixes the typo: "pendingText==master%20windows%20pending" (double equal) by https://github.com/cucumber/aruba/pull/469
Correct pending text of appveyor is good.
I will know that is right after merging.

Fix a typo for README appveyor badge image URL pending text.

---

.rubocop.yml
.travis.yml

Exclude files in vendor directroy for rubocop.
Because `bundle install --path vendor/bundle`
is a typical workflow for development.
When I run below commands, rubocop test is failed.
```
$ bundle install --path vendor/bundle
$ bundle exec rake test
```
`bundle install --path vendor/bundle` is also travis's default install command on Ruby language mode.
So, testing with `--path vendor/bundle` is better.
This fix promotes local development and contribution.
I tested it on my local. And Travis tests it.

Exclude files in vendor directroy for rubocop.

---

Rakefile

Reduce test output message to see the result from Travis page.
The `bundle exec rake cucumber`'s output is too long.
In general showing detail message on Travis looks good.
But in this case, bottom of the below page.
https://travis-ci.org/cucumber/aruba/jobs/258426780
> This log is too long to be displayed. Please reduce the verbosity of your build or download the raw log. 
Then seeing the raw log, it's hard to check by the color code.
So, currently the test output message does not work.
I think that a progress format is better to see the result from Travis page.
This promotes contribution.
Right now the hurdle may be high.
I check it on my local environment.
Also you can see the progress format on Travis page.

Reduce test output message to see the result from Travis page.

---

Rakefile

Use the RakeTask classes from Cucumber and RSpec to configure their Rake tasks in the `test` namespace.
- these tasks all have the same names as before
- and the same settings

Cucumber, RSpec rake tasks from their libraries

---

README.md
features/README.md

Another layout for the build badges in the readme
As pointed out in https://github.com/cucumber/aruba/pull/469 I think having a talble for the build status of "master" and "still" is easier to read. But I see the point in having some kind of a "sign post" for outsiders in what kind of state the project is.
This is why I moved up the "build" bages of the "master" branch.
I also added more details to clarify the use of the branches.
https://github.com/cucumber/aruba/tree/feature/other-layout-for-badges

Another layout for badges

---

features/03_testing_frameworks/cucumber/steps/command/check_for_exit_statuses.feature
features/04_aruba_api/filesystem/use_fixtures.feature
features/07_development_of_aruba/build-aruba.feature
lib/aruba/cucumber/command.rb

Fixes the remaining cucumber scenarios.
* Ensures at least one command is stopped before checking its exit status. Also updates the behavior described in the corresponding cucumber feature.
* Adjust the `should( not)? (pass|fail)` steps to do the same.
* Fix the aruba version matcher in the `build-aruba` feature.
* Fix the fixture feature not cause syntax errors and also actually run specs in each scenario.
This final change should make the full cucumber suite pass.
- Documentation fix

Fix final cuke failures

---

lib/aruba/cucumber/command.rb
lib/aruba/cucumber/hooks.rb
lib/aruba/rspec.rb
spec/aruba/api/deprecated_spec.rb
spec/aruba/api/environment/restore_env_spec.rb
spec/aruba/api/environment/set_env_spec.rb
spec/aruba/api/filesystem/file_size_spec.rb
spec/aruba/api_spec.rb
spec/aruba/matchers/deprecated_spec.rb
spec/aruba/matchers/directory_spec.rb
spec/aruba/matchers/path_spec.rb
spec/support/shared_contexts/aruba.rb

Ensures all non-deprecated Aruba API methods and steps only use non-deprecated methods. This way, the deprecation messages are actually useful.
* Block deprecation messages for specs of deprecated methods.
* Fix deprecation messages for specs of non-deprecated methods.
* TODO: Fix deprecation messages in cucumber scenarios.
Provide a (relatively) smooth transition from 0.14.x to upcoming 1.0.0. See also https://github.com/cucumber/aruba/issues/361#issuecomment-217751617.
Specs have been run and no warnings are observed.

Remove transitive deprecations

---

Gemfile

This is a workaround for #492.
By not installing `yard-junk` on Travis, we avoid installing a newer version of `did_you_mean` in the vendor directory, and hence avoid an activation error.

Move yard-junk out of :test group

---

aruba.gemspec

This PR removes unused, commented-out code in the gemspec.

gemspec: Remove commented-out code

---

cucumber.yml
features/03_testing_frameworks/cucumber/steps/command/check_output_of_command.feature
features/04_aruba_api/command/use_last_command_stopped.feature
features/step_definitions/hooks.rb
lib/aruba/api/command.rb
lib/aruba/api/core.rb
lib/aruba/config.rb
lib/aruba/cucumber/command.rb
lib/aruba/cucumber/hooks.rb
lib/aruba/platforms/command_monitor.rb
lib/aruba/rspec.rb
spec/aruba/api/deprecated_spec.rb

Aruba contains many conditionals on Aruba::VERSION. With the pending release of 1.0.0, many of these will forever be true (or false, as the case may be). This PR removes these conditionals and any old code that will remain unused.
Part of cleaning up stuff for the 1.0.0 release.
- Refactoring (cleanup of codebase withouth changing any existing functionality)

Remove conditionals that will remain fixed once 1.0.0 is released

---

.travis.yml
bin/console
features/02_configure_aruba/home_directory.feature
features/03_testing_frameworks/cucumber/steps/command/debug_your_command_in_aruba.feature
features/06_use_aruba_cli/open_console.feature
features/07_development_of_aruba/run-aruba-console.feature
features/step_definitions/hooks.rb

This fixes/skips the cucumber scenarios failing on OSX.
The following bits need fixing:
* ~Anything else that may turn up :-)~
~I have trimmed `.travis.yml` to be nice to Travis while this is still WIP. I'll remove that commit at the end.~
Making master green ...

Fix final OSX build failures

---

spec/aruba/api_spec.rb

Fixes an intermittent build failure.
Ensures the `env` command is done before inspecting its output.
Inspecting output without waiting for the command to be done sometimes causes the spec to fail because the desired output hasn't been produced yet. This caused intermittent Travis build failures. This problem is hard to reproduce locally.
I made the change similar to how other tests are done in the same spec file. Travis will be the judge.

Ensure env is done before inspecting output

---

lib/aruba/cucumber/file.rb

Fixes #424 by allowing slashes in file content matching regexes.
There seems to be no reason that slashes need to be disallowed in `%r` regex literals, and this prevents the not uncommon case of wanting to assert that a file's contents include file paths.
We've been running this patch in our testing environment for over a year, where it has definitely been working. Our Cucumber features contain expectations that match on file paths that include slashes.
I ran the aruba tests according to the instructions in https://github.com/cucumber/aruba/blob/master/CONTRIBUTING.md#getting-started-as-a-contributor. The only tests that failed were the Cucumber features that required `zsh`, which I don't have installed on my system.
I'm not sure if this change requires a test, since it's so simple, but …

Allow slashes in file matching regex

---

features/03_testing_frameworks/rspec/setup_aruba_for_rspec.feature
features/04_aruba_api/core/expand_path.feature
lib/aruba/api/core.rb

Make forgetting `setup_aruba` a hard failure
Forgetting to run `setup_aruba` resulted in a warning announcing that it would be a hard failure in 1.0.0. Kind of like 'deprecated', but with a twist. This PR makes the hard failure happen.
Part of getting ready for 1.0.0.
Scenarios that relied on the old behavior have been removed. The hard failure is not tested explicitly.

Make forgetting setup_aruba a hard failure

---

features/03_testing_frameworks/cucumber/steps/command/run_commands_which_require_a_shell.feature
lib/aruba/cucumber/command.rb

Fixes #513 
To avoid cucumber failures, marks scenarios requiring zsh, bash, python and ruby as such.
Also, avoids changing PATH when running ad-hoc scripts.
See #513.

Mark scenarios requiring external commands

---

features/03_testing_frameworks/cucumber/overview.feature

Remove scenario that does a full clone of the Aruba repository
This feature does an expensive clone of the aruba repository. In addition, steps should be documented in a nice format. We should not require users to clone our repo for this.
This change was also in #516.
- Update documentation

Remove cloning scenario

---

lib/aruba/platforms/unix_command_string.rb
lib/aruba/platforms/windows_command_string.rb
lib/aruba/processes/spawn_process.rb
spec/aruba/platforms/unix_command_string_spec.rb
spec/aruba/platforms/windows_command_string_spec.rb
spec/aruba/spawn_process_spec.rb

There was a bug in how `ChildProcess.build` was called. This PR fixes this for the `still` branch, backporting the changes from #520.
Calling `#to_a` was called on UnixCommandString representing the executable, splitting the name unnecessarily.
See #490.
A spec was added for this. This still needs to be tested on Windows.

Fix command spawning (still)

---

aruba.gemspec

Relax dependency to avoid problems with middleman gem.
Middleman requires an older dependency for contracts
(https://github.com/middleman/middleman/blob/master/middleman-core/middleman-core.gemspec#L56)
than aruba. Using Aruba >=
1.0.0.pre.alpha.x with Middleman does not work. Relaxing the dependency
a bit helps to avoid that problem.
I use middleman to generate and test proxy.pac-files. The test suite for https://github.com/fedux-org/proxy_pac_rb uses aruba and middleman.
Manually

Relax dependencies for contracts

---

lib/aruba/api/core.rb
lib/aruba/cucumber/hooks.rb
lib/aruba/setup.rb

When a scenario has @no-clobber, Aruba would not call Setup#call *at all*, which causes the
process monitor to not be listening to process events.
Changed Setup#call to accept a 'clobber' argument and set it according to whether there is @no-clobber or ~@no-clobber.
Closes #527
**THERE ARE NO TESTS YET** I'm just not sure where it is appropriate to test for this. It's weird to do this in a cucumber feature, as it's testing a regression and not a feature, but then we should check that @no-clobber and process monitoring work (which can only be done in cucumber). It's going to look weird in the cucumber.pro site, no ?

fix @no-clobber breaking process management (closes 

---

lib/aruba/api/core.rb
lib/aruba/cucumber/hooks.rb
lib/aruba/processes/spawn_process.rb
lib/aruba/setup.rb

The syntax in #529 and #490 is not compatible with Ruby 1.8.3. This PR fixes that.

FIx syntax to work with old rubies

---

features/01_getting_started_with_aruba/cleanup_working_directory.feature
lib/aruba/api/core.rb
lib/aruba/cucumber/hooks.rb
lib/aruba/setup.rb

Ensure setup is run even if files are not clobbered.
See #529.
Fixes #527.
Scenarios were updated to demonstrate that setup is also run when `@no-clobber` is set, but files are not clobbered.

Fix @no-clobber behavior

---

.travis.yml

Fix the build for Ruby 2.0.0 and 1.9.3 on OSX.
Ruby 2.0.0 and 1.9.3 cannot be installed on the default Travis CI OS X images. Use the xcode8 image instead, which uses OS X version 10.11 and Xcode version 8gm.
These builds were ignored and continuously failing, almost at the start of the build, making them effectively useless.
These settings yielded succesful builds in the experimental pull request #534.

Use known-good osx_image for old Rubies

---

lib/aruba/api/commands.rb
lib/aruba/command.rb
lib/aruba/processes/debug_process.rb
lib/aruba/processes/in_process.rb
spec/aruba/command_spec.rb
spec/aruba/processes/in_process_spec.rb
spec/aruba/processes/spawn_process_spec.rb

Ensure command output is only announced once.
During a run, `Command#stop` and `Command#terminate` are called multiple times, among other reasons to ensure all commands are actually terminated at the end of each spec or scenario.
If both general announcers and the announce-on-error functionality is used at the same time, duplicate output may still occur.
This includes changes from #399.
This fixes #374.
Specs were added by @maxmeyer and myself to ensure stop events are only broadcast once on the event bus. The behavior was confirmed by running some of Aruba's features by hand and examining the entire output produced.

Prevent duplicate output

---

lib/aruba/api/core.rb
spec/aruba/api_spec.rb

Fixes the behaviour of `#expand_path` when called with an absolute path.
Uses `File.expand_path` which has the desired behaviour.
Fixes #486.
A spec for this case was added to the test suite.

Restore expand_path behavior for absolute paths

---

spec/aruba/api/deprecated_spec.rb
spec/spec_helper.rb

Improve spec isolation by not blanket-including Aruba
Don't do `include Aruba` in the spec helper.
Less confusion in specs between modules and methods provided by the test environment and Ruby on the one hand, and Aruba on the other. Mainly just a back-port of a fix that's already on master.
Travis.
- Refactoring (cleanup of code base without changing any existing functionality)

Improve spec isolation by not blanket-including Aruba

---

cucumber.yml
features/03_testing_frameworks/cucumber/steps/command/stop_command.feature
features/step_definitions/hooks.rb

Clean up set of internally used cuke tags and their implementation.
* Remove one of the ways to indicate need for MRI platform
* Use only `hooks.rb` to define platform-related tag handling.
* Remove unused tags.
Clean up stuff.
Travis.

Clean up cuke tags

---

lib/aruba/matchers/deprecated.rb
lib/aruba/matchers/deprecated/file.rb
lib/aruba/matchers/file/have_same_file_content.rb
spec/aruba/matchers/deprecated_spec.rb
spec/aruba/matchers/file_spec.rb

Deprecated `have_same_file_content_like` and `a_file_with_same_content_like` matchers, and added `have_same_file_content_as` and `a_file_with_same_content_as matchers`, onto the `still` branch.
This is a modified version of https://github.com/cucumber/aruba/pull/555, applied to the `still` branch rather than `master`.
To make it easier to understand what the matchers do.
Added specs to ensure that the old and new matchers function correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cucumber/aruba/557)

Still Branch: Deprecated `have_same_file_content_like` and `a_file_with_same_content_like` matchers

---

CHANGELOG.md
lib/aruba/cucumber/file.rb
lib/aruba/matchers/file/have_same_file_content.rb
spec/aruba/matchers/file_spec.rb

Removed `have_same_file_content_like` and `a_file_with_same_content_like` matchers, and added `have_same_file_content_as` and `a_file_with_same_content_as`, as per https://github.com/cucumber/aruba/issues/485. The previous methods are deprecated in the HEAD of the `still` branch.
To make it easier to understand what the matcher does.
Added specs to ensure that the renamed methods are called.

Renamed `#have_same_file_content_like` matcher

---

lib/aruba/matchers/file/have_file_content.rb

This makes the `have_file_content` matcher `diffable` in cases when it's useful, without breaking existing behavior. 
Custom RSpec matchers aren't `diffable` by default. You have to manually specify that a matcher should be diffable. This change makes this `have_file_content` matcher `diffable`. In particular, it's important for files to be diffable, since they're likely going to be several lines, and RSpec will abbreviate the expectation / actual with a darned `...`.
I'm a core team member for [Hanami](hanamirb.org), and we used to use MiniTest for everything. We have since changed all our internal test suites to RSpec, but the generated projects still use MiniTest. I'm working on changing that, and there are a number of changes to generated files.
A big part of the Hanami ethos is to be …

Make have_file_content diffable

---

features/steps/environment/disable_bunder.feature
lib/aruba/api.rb
lib/aruba/api/bundler.rb
lib/aruba/api/rvm.rb
spec/aruba/api/bundler_spec.rb

Document `@disable-bundler` hook so it is not lost, and improve the implementation.
Backport of #560, basically.
#526.
Specs and a feature were added.

Document and fix @disable-bundler hook

---

features/03_testing_frameworks/cucumber/disable_bunder.feature
lib/aruba/api.rb
lib/aruba/api/bundler.rb
spec/aruba/api/bundler_spec.rb

Fix `@disable-bundler` hook
Restores the `unset_bundler_env_vars` method used by the `@disable-bundler` hook and adds documentation.
#526.
Specs and a feature file have been added.

Restore Bundler disabling functionality

---

History.md
lib/aruba/cucumber/file.rb

※ Pointing to `still` branch
Follow up on https://github.com/cucumber/aruba/pull/557: update the cucumber step to use the new matcher `have_same_file_content_as`.
Confirmed in https://github.com/cucumber/aruba/pull/557#issuecomment-416453305 that we missed to update the cucumber part to use the newly updated matcher.
Don't think there's any existing tests that I can work on...? 🤔 
And I know this is not scientific at all, I happen to update the gem for a project, and was able to use my patch to correctly compare the file content.
Also did a grep and confirmed all references of the now-deprecated matcher `have_same_file_content_like` are updated.
I updated the `History.md` file to jot down the change, feel free to modify it to your needs. 🙂
cc @mvz @xtrasimplicity

Fix Cucumber steps to use `have_same_file_content_as` matcher

---

spec/aruba/api_spec.rb

fix below test error (on Debian unstable)
> │ Run tests for ruby2.5 from debian/ruby-tests.rake                            │
>
> All examples were filtered out; ignoring {:focus=>true}
>      # ./spec/aruba/api_spec.rb:333:in `block (5 levels) in <top (required)>'
>
>      NoMethodError:
>        undefined method `parse' for Time:Class
>      Shared Example Group: "an existing directory" called from ./spec/aruba/api_spec.rb:388
>      # ./spec/aruba/api_spec.rb:386:in `block (7 levels) in <top (required)>'
>      # ./spec/aruba/api_spec.rb:381:in `block (6 levels) in <top (required)>'
>      # ./lib/aruba/rspec.rb:22:in `block (2 levels) in <top (required)>'
create debian package

add require time to avoid test failure

---

.travis.yml
Gemfile
aruba.gemspec

Update build matrix with Ruby 2.6.
Update Travis CI configuration to run tests on Ruby 2.6.0 series.
Ruby 2.6 has been released and we should test Aruba on it.

Test with Ruby 2.6

---

lib/aruba/api/commands.rb
spec/aruba/api_spec.rb

Properly warn about deprecation when passing one positional option to run methods.
Passing positional options to `#run_command` and `#run_command_and_stop` is deprecated, but this was not properly caught by the deprecation logic for the case where one options was passed.
Users should be able to fix their code before support for this is removed.
Specs where run and new deprecation warnings taken care of.

Fix deprecation edge case

---

README.md

This PR drops the Gemnasium badge from the README in the `still` branch.
It is removed.
The service is gone.

[still] README: Drop Gemnasium badge

---

Gemfile
aruba.gemspec

Update some dependencies
Updates dependencies on kramdown and childprocess
The dependency on childprocess is most important, because it affects users. Loosening our dependency on childprocess will allow them to use the latest childprocess in their projects. The update of kramdown is just nice for Aruba developers.
The update of kramdown was tested by running yardoc. That lead to a change in the Gemfile to explicitely depend on yard, since otherwise its presence in the bundle is only accidental. The change in the dependency on childprocess will be tested by Travis.

Update dependencies (still branch)

---

lib/aruba/processes/in_process.rb
spec/aruba/processes/in_process_spec.rb

fixes https://github.com/cucumber/aruba/issues/592
@olleolleolle

make FakeKernel#exit behave like real Kernel#exit

---

.travis.yml

CI matrix updated with latest GA JRuby version.
- and sudo: false is no longer a setting
We want to keep abreast of recent developments in JRuby that our users might be using.
This is a CI change, so it is tested on CI.

Travis: update to jruby-9.2.6.0, and to 2.6.1

---

.rubocop.yml
lib/aruba/api/deprecated.rb

Improve recommendation messages
- Attempt to recommend only non-deprecated alternatives
- Fix broken recommendations
- Wrap long lines to have overview of recommendations
- Warn about all methods in Deprecated module
Fixes #576.
- Update documentation

Improve deprecation messages

---

lib/aruba/api/core.rb
spec/aruba/api_spec.rb

Backport fix for `cd` behavior.
Test and fix the the setting of environment variables inside the block passed to `cd`. Backport of cbbefda22343ee8a858cc6e0ce85446b107b5609, which was part of #442.
The `#cd` method would clear the entire environment within the block, instead of just updating it. This is clearly not the intended behavior, since even variables set with `set_environment_variable` are ignored. This also makes `#cd` a bad substitute for the deprecated `#in_current_directory` method.
Specs were added.

Do not replace entire environment inside cd block

---

features/README.md

This PR updates the README seen by people browsing Jam: https://jam.cucumber.io/projects/aruba/documents/branch/master
This README has not been updated in a while.
One of the badges' service has been closed since then.
We want the information shown to be relevant and current.

README seen in Jam: Drop Gemnasium badge

---

.travis.yml

This updates the CI matrix to use latest releases of Rubies.

CI: Use 2.4.6, 2.5.5, 2.6.3, jruby-9.2.7.0

---

lib/aruba/config/jruby.rb
spec/aruba/jruby_spec.rb

Make the JRuby before command helper modify the Aruba environment, rather than the real one.
The JRuby helper sets up a `before :command` hook to set helpful environment variables for JRuby. This changes makes the helper use `set_environment_variable` to set Aruba's environment rather than directly modifying the real one.
When the environment is modified directly, this causes unexpected behavior when using `with_environment`, since that methods will base the changed environment on the environment at startup, rather than the current one. Therefore, `with_environment` will unexpectedly undo such modifiections.
All this came to light while working on #603.
Tests for the JRuby helper were updated to check the result inside a `with_environment` block, thus mimicing the behavior when the hook …

Make JRuby before command hook work on Aruba environment

---

features/08_other/improve_performance_if_using_jruby.feature
lib/aruba/api/core.rb
lib/aruba/config/jruby.rb
spec/aruba/jruby_spec.rb

Add full integration test for JRuby helper and make it work.
The before :command hooks are run after the command's environment has already been set up, so instead of modifying Aruba's environment, of the actual environment, we need to modify the command's environment. This change adds a scenario for this feature, and updates the implementation
to make it work.
We also no longer require the helper by default, so requiring by the user will have the desired effect.
An attempt was made to fix this feature in #610, but it lacked an integration test so it failed.
A scenario was added and the specs were updated.

Fix JRuby before :command helper hook 

---

appveyor.yml
features/02_configure_aruba/command_runtime_environment.feature
features/05_use_rspec_matchers/path/have_permissions.feature
fixtures/spawn_process/stderr.sh
lib/aruba/configuration.rb
lib/aruba/platforms/local_environment.rb
lib/aruba/platforms/unix_command_string.rb
lib/aruba/platforms/unix_environment_variables.rb
lib/aruba/platforms/windows_command_string.rb
lib/aruba/platforms/windows_environment_variables.rb
lib/aruba/processes/basic_process.rb
lib/aruba/processes/in_process.rb
lib/aruba/processes/spawn_process.rb
lib/aruba/rspec.rb
spec/aruba/matchers/command_spec.rb
spec/aruba/matchers/path_spec.rb
spec/aruba/platforms/unix_command_string_spec.rb
spec/aruba/platforms/windows_command_string_spec.rb
spec/aruba/processes/spawn_process_spec.rb
spec/aruba/rspec_spec.rb

Work towards a green build on AppVeyor for just the specs
* Build on supported Ruby versions
* Run only the spec part of the test suite
* Fix specs
I want to get at least part of #505 merged but the cucumber part is tough.
Specs have been run on Linux, AppVeyor will check Windows.

Improve appveyor build: Specs part

---

.rubocop.yml
.travis.yml
Gemfile
features/03_testing_frameworks/cucumber/steps/command/run_commands_which_require_a_shell.feature
features/step_definitions/hooks.rb
features/support/env.rb
features/support/simplecov_setup.rb
script/bootstrap
spec/aruba/api_spec.rb
spec/spec_helper.rb

Several improvements to how we build on Travis CI.
* Drop zsh as a build dependency (improves related scenarios as well)
* Fix caching of bundle
* Fix testing on JRuby versions
* Some cleanups
Our builds are very slow. At least we should build what is relevant.
Travis is working on it.

Improve build set for still branch

---

aruba.gemspec

This reduces unnecessary redirection from http://... to https://... when someone visits this gem's homepage via https://rubygems.org/gems/aruba or some tools or APIs that use the gem metadata.

GitHub is HTTPS by default

---

lib/aruba/cucumber/command.rb

Ruby stdlib Timeout's TimeoutError is deprecated in favor of Timeout::Error.
https://github.com/ruby/ruby/blob/34d7ec4e9b0a24b3ce89009927738f1dac38e6d3/lib/timeout.rb#L125-L130

TimeoutError is deprecated in favor of Timeout::Error

---

aruba.gemspec

Loosen dependency on Cucumber to allow use of Aruba with Cucumber 3.x.
Fixes #625.
Tests were run with updated bundle.

Allow use with Cucumber 3.x

---

lib/aruba/cucumber.rb
lib/aruba/cucumber/command.rb
lib/aruba/cucumber/deprecated.rb
lib/aruba/cucumber/file.rb
lib/aruba/cucumber/hooks.rb

Move deprecated cucumber steps into a separate file
Move deprecated cucumber steps into `lib/aruba/cucumber/deprecated.rb`.
Part of #598. This will make merging easier.
Travis.

Move deprecated cucumber steps into a separate file

---

.travis.yml

Test on CRuby 2.3.0.
Adds target CRuby 2.3.0 on Linux to Travis CI
We officially support Ruby 2.3 and up, so we need to make sure Aruba actually works there. There are some dependency versions that support, e.g., 2.3.3 and up, so this is not an academic exercise.
Travis CI will do its thing.

Test on lowest supported Ruby version

---

lib/aruba/colorizer.rb
lib/aruba/platforms/announcer.rb

Implements a simple Aruba::Colorizer class to color stuff cyan.
See #627 and its discussion for details.
This is basically a refactoring.

Replace problematic AnsiColor module with simple implementation

---

features/08_other/improve_performance_if_using_jruby.feature
lib/aruba/api/core.rb
lib/aruba/config/jruby.rb
spec/aruba/jruby_spec.rb

Add full integration test for JRuby helper and make it work.
The before :command hooks are run after the command's environment has already been set up, so instead of modifying Aruba's environment, or the actual environment, we need to modify the command's environment. This change adds a scenario for this feature, and updates the implementation to make it work.
We also no longer require the helper by default, so requiring by the user will have the desired effect.
This is a forward-port of #612.
Cucumber scenario and RSpec specs were added.

Fix JRuby before :command helper hook

---

lib/aruba/in_process.rb
lib/aruba/spawn_process.rb

Warn when deprecated files `aruba/in_process` and `aruba/spawn_process` are required.
Fixes #630.
```bash
bundle exec ruby -e "require 'aruba/in_process'"
```
I'm confused. We may need a new category for this :confused:

Warn when deprecated files are required

---

features/03_testing_frameworks/cucumber/steps/command/check_output_of_command.feature
features/03_testing_frameworks/cucumber/steps/command/check_stderr_of_command.feature
lib/aruba/api/commands.rb
lib/aruba/api/core.rb
lib/aruba/api/deprecated.rb
lib/aruba/cucumber/command.rb
lib/aruba/matchers/string/output_string_eq.rb
lib/aruba/platforms/command_monitor.rb
spec/aruba/api/core_spec.rb

Restores `#all_output`, `#all_stdout`, `#all_stderr` and `#in_current_directory` API methods to non-deprecated status. Also un-deprecates the current behavior of output-checking cucumber steps.
* These API methods seem to be the deprecated methods most used by downstream projects, and their replacements are more complex.
* The output-checking cucumber steps are currently set to have a breaking change in 1.0.0 and we should instead have a smooth upgrade path that will allow moving from latest 0.14.x to 1.0.0 when the latter is released.
* The replacement cucumber steps in master currently have less useful output, and the current behavior is more intuitive.
Some tests were added but mostly code was just moved.

Undeprecate some stuff

---

.rubocop_todo.yml
.travis.yml
Gemfile
Rakefile
aruba.gemspec
fixtures/cli-app/cli-app.gemspec
fixtures/empty-app/cli-app.gemspec
fixtures/getting-started-app/Gemfile
spec/spec_helper.rb

Tidy up Gemfile / Deps
Migrate everything that could be out of gemfile conditionals into gemspec fixed values.
NB: I've also updated a few minor version restrictions. And the *minimum ruby version* although this was always 2.3.3 due to a dependency requirement.
Tidies things up.
CI

Gemfile/Gemspec Tidy (For Master)

---

lib/aruba/cucumber/command.rb
lib/aruba/platforms/command_monitor.rb
spec/aruba/api/commands_spec.rb
spec/aruba/api/core_spec.rb
spec/aruba/api_spec.rb

Backport some small fixes and cleanups from master
Just some small things I fixed while working on #644. Also demonstrates that #608 is not a problem.

Backport fixes

---

features/03_testing_frameworks/cucumber/steps/command/check_output_of_command.feature
lib/aruba/api/commands.rb
lib/aruba/api/core.rb
lib/aruba/cucumber/command.rb
lib/aruba/matchers/command/have_exit_status.rb
lib/aruba/matchers/command/have_finished_in_time.rb
lib/aruba/matchers/command/have_output.rb
lib/aruba/matchers/command/have_output_on_stderr.rb
lib/aruba/matchers/command/have_output_on_stdout.rb
lib/aruba/matchers/command/have_output_size.rb
lib/aruba/matchers/directory/be_an_existing_directory.rb
lib/aruba/matchers/file/be_an_existing_file.rb
lib/aruba/platforms/command_monitor.rb
spec/aruba/api/core_spec.rb

Restore behaviors in master whose deprecation in 0.1.4.x was reverted.
* Restore the API methods `#in_current_directory`, `#all_stdout`, `#all_stderr`, `#all_output`.
* Raise an error in output matchers when actual object does not respond to required methods. Previously, the matcher would just fail.
* Restore old behavior for output-matching cucumber steps, splitting them up a bit as well.
Fixes #641.
Tests in 0.14.x for `#in_current_directory` were copied as well. The other methods are only tested throught the cucumber scenarios at the momen.

Restore previously removed behaviors

---

features/step_definitions/hooks.rb

Stop checking for Cucumber::VERSION below 2.
Removes some outdated checks for the cucumber version from Aruba's hooks. Cucumber below 2.4 is no longer supported per the gemspec.
Cleaning up.

Remove checks for now-unsupported Cucumber version

---

features/support/jruby.rb
lib/aruba/api/deprecated.rb

Improve deprecation messages to make them more easily actionable.
Suggests replacements that more directly match the originals.
Upgrading Aruba for some rspec repositories, I noticed the suggested replacements were not specific enough and did not match the arguments of the originals.
N/A

Improve deprecations

---

lib/aruba/processes/spawn_process.rb

Let Ruby handle line ending conversion, making use of Aruba easier for Windows users
SpawnProcess used to set binmode on the tempfiles used to capture stdout and stderr. This was done to fix failures on JRuby. This is removed to allow line endings to be handled automatically. The JRuby failures are fixed by setting the encoding on the tempfiles instead.
This fixes #614.
Basically, by running the test suite on Travis. The original change to binmode was badly tested as well.

Do not set binmode on output temp files

---

lib/aruba/platforms/unix_platform.rb
lib/aruba/platforms/windows_platform.rb
lib/aruba/processes/spawn_process.rb

Support windows internal commands by accepting them as existing commands.
Allow SpawnProcess to find built-in shell commands in addition to real executable files. Provide list of such built-in commands for Windows.
* This was implemented as part of #505
* Fixes #568
TBA

Support windows internal commands

---

features/03_testing_frameworks/cucumber/steps/command/debug_your_command_in_aruba.feature
lib/aruba/processes/debug_process.rb

Improve documentation for `@debug`
Improving documentation is an ongoing process.
- Update documentation

Improve documentation for @debug

---

features/03_testing_frameworks/cucumber/steps/command/debug_your_command_in_aruba.feature
features/06_use_aruba_cli/open_console.feature
lib/aruba/cucumber/command.rb

The build was broken in #656. This PR fixes that.
* Changes the annotation for the debug feature to not run it on JRuby. Running a debugger in the DebugProcess runner doesn't actually allow interacting with in on JRuby.
* Changes the annotation for some other scenarios that actually run fine on JRuby.
* Cleans up a useless assignment to `@interactive`.
The build is currently broken in master.
The relevant scenarios were run on JRuby and MRI.

Fix up JRuby build

---

Gemfile
aruba.gemspec

Allow end-users to use childproces 2.0.0 on recent Rubies
* Loosen dependency on childprocess.
* Adjust Gemfile to allow childprocess 2.0.0 on recent Rubies.
Allows users to stay up-to-date.
Tests are run with new version 2.0.0 of childprocess on Travis CI for compatible Ruby versions.

Loosen childprocess dependency

---

.rubocop.yml
.rubocop_todo.yml
aruba.gemspec
lib/aruba/api/core.rb
lib/aruba/api/environment.rb
lib/aruba/api/filesystem.rb
lib/aruba/config_wrapper.rb
lib/aruba/configuration.rb
lib/aruba/matchers/command/have_exit_status.rb
lib/aruba/platforms/windows_environment_variables.rb
lib/aruba/processes/spawn_process.rb
spec/aruba/api/filesystem_spec.rb

Attempt to begin to fix the vast quantity of LineLength offenses (Some are 250+ chars)
Manually tweak some lines to get some quick wins, tackle the largest offenders first.
To try get the `master` branch under better rubocop conformation
CI

Fix up a few of the LineLength cops

---

lib/aruba/cucumber/file.rb

Allow both 'a' and 'the' in file mode checking step, as documented in the corresponding feature file.
Updates the step regexp to allow both 'a' and 'the' at the start. So, now 'a file named ...' is properly matched.
Oddly, on JRuby 9.2.7.0, cucumber fails on undefined steps. This made the feature for this step fail and surfaced the problem.
Nothing yet. We need to have some way to detect undefined steps better.

Allow both 'a' and 'the' in step, as documented

---

features/03_testing_frameworks/cucumber/announce_information_for_troubleshooting.feature
features/03_testing_frameworks/cucumber/steps/command/debug_your_command_in_aruba.feature
lib/aruba/platforms/announcer.rb
lib/aruba/processes/basic_process.rb
lib/aruba/setup.rb

Handle announcing with the DebugProcess runner
The DebugProcess runner does not implement all methods used by the announcer (and the same goes for the InProcess runner). Catch the resulting NotImplementedError exceptions and print an appropriate message.
Issue #563. 
A cucumber scenario was added.

Handle announcing with DebugProcess

---

.travis.yml
CONTRIBUTING.md
Rakefile
appveyor.yml
bin/build
bin/release

Clean up Rakefile and Travis config
* Remove some namespacing from Rakefile
* Remove explicit locale setting from Travis configuration
* Update build configuration with new task names
* Update documentation with new task names
* Remove trivial helper scripts
While investigating #477, I was again annoyed by Aruba's non-standard Rake task names.
N/A

Clean up build

---

.travis.yml

Use Ubuntu trusty so old Rubies can be installed. May help with the JRuby failures, too.
Travis configuration update taken from https://github.com/rspec/rspec-core/blob/8e3ce245a78c8c55eeda0bc5928f68731a2fa206/.travis.yml#L5
Failing builds

Use trusty distribution on Travis CI (still branch)

---

lib/aruba/cucumber/command.rb
lib/aruba/cucumber/file.rb
lib/aruba/cucumber/testing_frameworks.rb

Partially fix up the highly coupled / split steps in aruba
Where a step had 4/5/6 block params, I've opted to duplicate the cukes but reduce complexity. I've not done them all, but done sufficiently enough to improve the codebase
Partially fixes https://github.com/cucumber/aruba/issues/640
CI

Refactor: Uncouple some of aruba's step definition code

---

.travis.yml

Use latest JRuby in Travis build
Bump JRuby version to 9.2.8.0 for the Linux and OSX builds.
We were testing on 9.2.6 because 9.2.7 broke scenario skipping in Cucumber. Now that 9.2.8 is out we should be able to safely move to that.
I broke this out from #670 since setting the JAVA_OPTS correctly turns out to be more difficult than I anticipated.
Travis will do its thing.

Bump JRuby 9.2 build version

---

lib/aruba/platforms/unix_platform.rb

This PR suppresses the following keyward argument warnings when using Ruby 2.7.
```console
% ruby -v
ruby 2.7.0dev (2019-09-12T15:35:29Z master 69acf40b45) [x86_64-darwin17]
% bundle exec rake
(snip)
/Users/koic/src/github.com/cucumber/aruba/lib/aruba/platforms/unix_platform.rb:116:
warning: The last argument is used as the keyword parameter
/Users/koic/.rbenv/versions/2.7.0-dev/lib/ruby/2.7.0/fileutils.rb:605:
warning: for `rm_r' defined here
/Users/koic/src/github.com/cucumber/aruba/lib/aruba/platforms/unix_platform.rb:135:
warning: The last argument is used as the keywo
rd parameter
/Users/koic/.rbenv/versions/2.7.0-dev/lib/ruby/2.7.0/fileutils.rb:1120:
warning: for `touch' defined here
./Users/koic/src/github.com/cucumber/aruba/lib/aruba/platforms/unix_platform.rb:150:
warning: The …
```

Suppress keyward argument warnings in Ruby 2.7

---

Gemfile
aruba.gemspec

Loosen dependency on childprocess
Update dependencies to allow childprocess 3.0. Adjust Gemfile to install newer versions on compatible rubies.
Allows downstream projects to update their childprocess dependency.
Travis.

Loosen dependency on childprocess

---

lib/aruba/matchers/command/be_successfully_executed.rb

Show useful debugging information when the `:be_successfully_executed` matcher fails.
I was debugging a cucumber suite, and getting this error:
```
Using the default profile...
.F-----------
(::) failed steps (::)
expected "bundle exec rake part1" to be successfully executed (RSpec::Expectations::ExpectationNotMetError)
/home/deivid/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-support-3.9.0/lib/rspec/support.rb:97:in `block in <module:Support>'
/home/deivid/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-support-3.9.0/lib/rspec/support.rb:106:in `notify_failure'
/home/deivid/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.9.0/lib/rspec/expectations/fail_with.rb:35:in `fail_with'
/home/deivid/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rspec-expectations- …
```

Improve command failure message

---

features/02_configure_aruba/command_runtime_environment.feature
features/02_configure_aruba/root_directory.feature

Setting root_directory will no longer be supported in 1.0.0. Mark it as deprecated in the cucumber scenario.
**This was originally the main pull request for #598. Original description follows**
Update the `still` development branch so the change to `master` is no more than a removal of deprecations.
**This is a work in progress**. This is a combination of backporting bug fixes, moving deprecated code, moving other files. The end goal is that merging `still` into `master` will only lead to conflicts in deleted files that contain the code deprecated in the `0.14.x` line and removed in `1.0.0`.
A lot of projects that use Aruba are not even on `0.14.x` yet. We should be able to tell them that they should do that and fix all deprecations, and then they should be able to safely move to upcoming …

Mark setting of root directory as deprecated

---

.rubocop.yml
.travis.yml
appveyor.yml
aruba.gemspec
features/03_testing_frameworks/cucumber/steps/command/check_for_exit_statuses.feature
features/04_aruba_api/command/read_stderr_of_command.feature
features/04_aruba_api/command/run_command.feature
features/04_aruba_api/command/run_simple.feature
features/06_use_aruba_cli/open_console.feature
lib/aruba/platforms/unix_platform.rb
lib/aruba/processes/spawn_process.rb

Drop support for Ruby 2.3 in master, so Aruba 1.0.0 will target 2.4+
Updates build set on Travis, and sets minimum supported version in gemspec and RuboCop config.
Ruby 2.3 has been deprecated for a long time, we can't get the JRuby 9.1 build working on Travis' Xenial environment, and even 2.4 is nearing its end-of-life.
Travis will run it!

Update supported set of rubies

---

lib/aruba/initializer.rb

When you run `aruba init --test-framework cucumber` in the root of a project with a Gemfile that does _not_ end with a carriage return, it appends `gem 'aruba' ...` to the end of the previous line.
In this PR, if the Gemfile ends with a carriage return it appends it to the final line. If the Gemfile doesn't end with a carriage return, it prepends a carriage return to ensure that `gem 'aruba' ...` is always on a new line.
This resolves #430.
I've added a simple check and conditionally prefixed a carriage return.
This solves https://github.com/cucumber/aruba/issues/430
This uses the existing tests, but I can add additional tests. :+1:

Init: Conditionally prefix the `gem aruba` line with a carriage return.

---

cucumber.yml

This PR fixes several cucumber deprecations.
In particular,
```
Deprecated: Found tags option '~@unsupported-on'. Support for '~@tag' will be removed from the next release of Cucumber. Please use 'not @tag' instead.
Deprecated: Found tags option '~@wip'. Support for '~@tag' will be removed from the next release of Cucumber. Please use 'not @tag' instead.
Deprecated: Found tags option '~@ignore'. Support for '~@tag' will be removed from the next release of Cucumber. Please use 'not @tag' instead.
```
Warnings are annoying and can get things broken in the future.
Running aruba's tests.

Fix cucumber deprecations

---

Rakefile
aruba.gemspec

The previous library being used seems abandoned and not really working.
Before:
```console
$ bundle exec rake lint:travis
Linting .travis.yml ... No output is good!
.travis.yml: unexpected key "jobs", dropping
```
After:
```console
$ bundle exec rake lint:travis
Linting .travis.yml ...
travis lint
Hooray, .travis.yml looks valid :)
```

Fix travis.yml lint task

---

appveyor.yml

Remove an uneeded appveyor step.
The appveyor script always installs `ansicon` (ANSI control sequences library).
This step can fail sometimes, so removing it should make the build more reliable and faster.
I created this PR because [this appveyor build](https://ci.appveyor.com/project/cucumberbdd/aruba/builds/29844043/job/p2vvugowi47p35wx) failed because of this unnecessary step.

Remove unneeded appveyor step

---

.travis.yml
Gemfile

* Remove debug group since bundler's --without option is deprecated
* Build on latest jruby 9.2
* Remove old stale branch from branch list

Update build configuration

---

CONTRIBUTING.md
Rakefile
aruba.gemspec
lib/aruba/platforms/unix_environment_variables.rb
spec/aruba/api/core_spec.rb

* Remove Travis YML linting
* Make all RuboCop warnings failures
* Fix environment nesting
I don't want RuboCop warnings to pile up, and the Travis gem introduces a lot of outdated dependencies. Fixing the RuboCop warnings found a bug in the new environment nesting code.
The lint task was run locally, and a new spec was added.

Clean up linting and fix environment nesting

---

features/03_testing_frameworks/cucumber/steps/command/check_for_exit_statuses.feature
features/03_testing_frameworks/cucumber/steps/command/run_a_command.feature
features/04_aruba_api/command/run_command.feature
lib/aruba/api/commands.rb
spec/aruba/api/commands_spec.rb

Find relative commands from the current Aruba directory
In an Arabu spec or scenario, files are created relative to the current Aruba directory. When creating an executable in that way, it should be possible to run that executable using the same relative path.
This change means that executables in the project under test can no longer be find using the relative path from the project directory. They should be added to the path. This is done automatically by Bundler.
Technically this is accomplished by doing the command lookup inside an `in_current_directory` block.
Fixes #552. 
Specs and cukes were added.

Find relative commands from the current Aruba directory

---

features/02_configure_aruba/home_directory.feature
features/03_testing_frameworks/cucumber/steps/command/check_output_of_command.feature
features/03_testing_frameworks/cucumber/steps/command/check_stderr_of_command.feature
features/03_testing_frameworks/cucumber/steps/command/check_stdout_of_command.feature
features/03_testing_frameworks/rspec/setup_aruba_for_rspec.feature

Several improvements to cucumber scenarios
* Fix a spelling error
* Add extra scenarios to confirm output from multiple commands is checked the same way as in 0.14.x. These were taken from the 0-14-stable branch
* Improve wording of cukes home_directory to match with what's really going on
The big part is confirming no change in output handling w.r.t. 0.14.x.
Scenarios were run.

Several cuke improvements

---

lib/aruba/api/commands.rb
lib/aruba/api/filesystem.rb

Avoid some warnings and misprints in API docs
YARD.
I noted when generating docs that we had some warnings. I took a look at one of them, and managed to improve it.
```
lib/aruba/api/commands.rb:171: [UnknownParam] @param tag has unknown parameter name: options
lib/aruba/api/filesystem.rb:143: [UnknownParam] @param tag has unknown parameter name: file_name
lib/aruba/api/filesystem.rb:163: [UnknownParam] @param tag has unknown parameter name: source
lib/aruba/api/filesystem.rb:168: [UnknownParam] @param tag has unknown parameter name: destination
lib/aruba/api/filesystem.rb:209: [UnknownParam] @param tag has unknown parameter name: source
lib/aruba/api/filesystem.rb:214: [UnknownParam] @param tag has unknown parameter name: destination
lib/aruba/api/filesystem.rb:287: [UnknownParam] @param …
```

doc: Repair YARD annotations

---

fixtures/cli-app/cli-app.gemspec
fixtures/empty-app/cli-app.gemspec

This old version of Rake has security issues. Avoid referencing it and tripping up security scanners.
Bump rake versions in gemspec files used for testing.
GitHub's security scanner was complaining.
Travis ...

Stop depending on ancient Rake in fixtures

---

.rubocop.yml
aruba.gemspec
lib/aruba/platforms/unix_environment_variables.rb
spec/aruba/api/filesystem_spec.rb

Update to RuboCop 0.82 and autocorrect new offenses
* Update RuboCop dependency to 0.82
* Enable new cops from RuboCop 0.80-0.82 
* Autocorrect new offenses
Keeps stuff up-to-date.
I ran RuboCop.

Update RuboCop and correct new offenses

---

aruba.gemspec

Loosen dependency on RuboCop
Makes the dependency allow any later pre-1.0 version of RuboCop. RuboCop will not activate any new cops by default before the 1.0 release, so this should be perfectly safe.
Don't require updating dependencies every time a new minor RuboCop release happens.
There's not much to test at the moment.
- Developer experience

Update and loosen dependency on RuboCop

---

aruba.gemspec

Update rubocop dependencies
- Update rubocop to 0.90.0
- Update rubocop-packaging to 0.4.0
- Update rubocop-performance to 1.8.0
Keeps things up-to-date.
I ran rubocop
- Update dependencies

Update rubocop dependencies

---

.github/dependabot.yml
.travis.yml

Update to the development infrastructure to reduce repetitive work and waiting
- Configure Dependabot, so dependency updates are done mostly automatically
- Restructure Travis build tasks to reduce waiting
Making pull requests just to keep the dependencies updated is boring, so let's make the cloud do it. Also, the sooner Travis is done building the better.
We'll know if it works once Travis does its thing
- Developer experience improvement

Update development infrastructure

---

.travis.yml

Turn off this warning by following its advice:
```
┌──────────────────────────────────────────────────────────────────────────┐
│ Share your Cucumber Report with your team at https://reports.cucumber.io │
│                                                                          │
│ Command line option:    --publish                                        │
│ Environment variable:   CUCUMBER_PUBLISH_ENABLED=true                    │
│ cucumber.yml:           default: --publish                               │
│                                                                          │
│ More information at https://reports.cucumber.io/docs/cucumber-ruby       │
│                                                                          │
│ To disable this message, specify …
```

CI: Turn off Cucumber publish warning

---

aruba.gemspec
spec/aruba/matchers/collection_spec.rb

Update matcher specs for changed RSpec failure message.
RSpec 3.10 chnages some failure messages. Require this version explicitly and update the expected messages in the relevant specs.
Specs started failing unexpectedly.
Ran the full suite.

Update matcher specs for changed RSpec failure message

---

aruba.gemspec
lib/aruba/basic_configuration.rb
spec/aruba/api/core_spec.rb
spec/aruba/processes/in_process_spec.rb
spec/event_bus_spec.rb

Update RuboCop depenencies and fix new offenses
Update `rubocop` and `rubocop-rspec` and fix `Lint/EmptyBlock` offenses.
Keep things up-to-date. A hand-rolled pull request is needed because both dependencies need to be updated at the same time.
I ran RuboCop

Update RuboCop depenencies and fix new offenses

---

features/02_configure_aruba/exit_timeout.feature
features/03_testing_frameworks/cucumber/steps/command/send_signal_to_command.feature

Make some changes to cucumber features to ensure MacOS runners succeed
in CI.
- Increase timeout values in cucumber features
MacOS builds fail regularly. This seems to be timeout related.
The CI runners have to run to check this. More changes may be needed to
make them all pass.

Make Cucumber features more robust on MacOS CI runners.

---

.travis.yml

Travis was set up to build only on the master and still branches, but we don't use still anymore. So instead, build on 0-14-stable.
Just changed the TravisCI config to replace still with 0-14-stable
Let's see if we can get TravisCI to build the last few pull requests on 0-14-stable before travis-ci.org goes down.
Travis will hopefully build ...
- Project support files.

Build 0-14-stable branch on Travis CI

---

aruba.gemspec

Loosen dependency on simplecov
The dependency of simplecov is a bit hard for dependabot to update automatically.
Updated the bundle and ran the specs.
- Update development infrastructure

Loosen dependency on simplecov

---

.github/workflows/ruby.yml
.rubocop.yml
Gemfile
Rakefile
lib/aruba/api/commands.rb
lib/aruba/api/deprecated.rb
lib/aruba/api/filesystem.rb
lib/aruba/cucumber/deprecated.rb
lib/aruba/matchers/base/object_formatter.rb
lib/aruba/platforms/announcer.rb
lib/aruba/platforms/unix_platform.rb
spec/aruba/api/core_spec.rb

Don't run RuboCop so much: Once is enough.
- Run RuboCop in a GitHub Actions job
- Remove RuboCop run from the TravisCI builds
- Remove travis:lint task
Make test run faster, use as little TravisCI as possible.
Running the builds.
- Dev infrastructure

Run rubocop only once (0-14-stable branche)

---

.github/workflows/ruby.yml

Set JRUBY_OPTS to `--dev` in GitHub Actions
This setting got lost in the move from Travis CI to GitHub Actions. Setting this makes a huge difference in Aruba's case because the cucumber features launch a lot of Ruby processes.
- Dev infra

Set JRUBY_OPTS for speedier tests

---

features/03_testing_frameworks/cucumber/disable_bunder.feature
features/04_aruba_api/command/run_simple.feature
fixtures/cli-app/Gemfile
fixtures/cli-app/cli-app.gemspec
fixtures/empty-app/cli-app.gemspec
lib/aruba/api/bundler.rb

Use Bundler's tooling to break out of the main bundle
The `@disable_bundler` tag doesn't always work very well because it just guesses at what enironment variables to disable. Use
`Bundler.with_unbundled_env` instead to find the exact set of environment variables to change.
Inspired by #699. While getting `keep_up` to build with GitHub Actions I found out that the simple method of unsetting the environment variables does not work in all cases. See https://github.com/mvz/keep_up/pull/40.
I ran the updated feature file.

Make disabling Bundler more robust

---

features/03_testing_frameworks/cucumber/disable_bunder.feature
fixtures/cli-app/Gemfile
fixtures/cli-app/cli-app.gemspec
fixtures/empty-app/cli-app.gemspec
lib/aruba/api/bundler.rb

Use Bundler's own tooling to break out of the Bundler environment, instead of just unsetting a bunch of environment variables.
Use `Bunder.with_unbundled_env` to inform us how manipulate the environment instead of guessing ourselves: We fetch the environment inside the `Bunder.with_unbundled_env` block and record the changes that were applied. Then we manipulate Aruba's environment to have the same changes.
#699.
Let's see what TravisCI has to say ...

Disable bundler using bundler tooling (0-14-stable)

---

.github/workflows/ruby.yml

Add Ruby 3.0 to the list of Rubies to test on with GitHub Actions
Ruby 3.0 is out!

Run tests on Ruby 3.0 in CI

---

spec/aruba/jruby_spec.rb

Fix JRuby support specs when using rspec-expectations 3.10.1
The latest version of rspec-expectations added a check for JRUBY_VERSION to its implementation of aggregate_failures, so stub that constant as well in order to succesfully pretend to run on JRuby.
Build failures for #764
Ran the relevant specs, watched them pass again.

Fix JRuby support specs when using rspec-expectations 3.10.1

---

.gitignore
lib/aruba/api/commands.rb
lib/aruba/basic_configuration.rb
spec/aruba/jruby_spec.rb
spec/support/configs/rspec.rb

Clean up hook methods
- Use separate methods for defining and running hooks
- Remove unused methods for checking if hooks are defined
Makes the hook methods more robust by making them require the arguments
needed for the narrower context in which each of them is used.
Simplifies the code in the hook methods by having to deal with fewer
cases.
Running the tests.

Clean up hook methods

---

.github/workflows/ruby.yml
aruba.gemspec
features/01_getting_started_with_aruba/run_commands.feature
features/02_configure_aruba/basics.feature
features/03_testing_frameworks/cucumber/disable_bundler.feature
features/04_aruba_api/command/terminate_all_commands.feature
features/step_definitions/hooks.rb
lib/aruba/platforms/filesystem_status.rb
lib/aruba/platforms/unix_platform.rb
lib/aruba/platforms/windows_platform.rb
spec/aruba/api/commands_spec.rb

Several measures to improve test suite speed; Some also improve test suite speed for Aruba's users.
- Remove some slow scenarios
- Don't let bundle access network inside scenario
- Lower some timeouts again
- Don't load FFI just to check platforms
- Don't use Forwardable: Its method creation is slow
Slow test suite is slow.
Ran the specs and the changed cukes.

Speed up test suite for Aruba and its users

---

lib/aruba/basic_configuration.rb
lib/aruba/configuration.rb
spec/aruba/configuration_spec.rb
spec/support/shared_examples/configuration.rb

Remove redundant type specifications in configuration reader and
accessor specifications
Adjust the configuration specification DSL so the type of the option
only needs to be specified once.
Cleans up the codebase and is one step toward removing the dependency on
the contracts gem (see #770).
I ran the specs.

Simplify configuration specification

---

Rakefile

Check the manifest as part of the linting task
Add the `manifest:check` task as a dependency of `lint`.
It's good to know this is broken way before trying to push a release.
Ran the task.
- Developer experience improvement

Check the manifest as part of the linting task

---

features/04_aruba_api/command/read_stderr_of_command.feature
features/04_aruba_api/command/read_stdout_of_command.feature

Increase io_wait_timeout a little larger so it's not exceeded during
MacOS cucumber runs in CI.
Increase io_wait_timeout in one cucumber scenario. Also remove pointless
setting of that value outside of the fixture app directory.
Somehow it seems there's always at lease one MacOS build failing.
I ran the scenarios locally but that doesn't really tell much.

Give stderr output example a little more time

---

aruba.gemspec

Allow simplecov 0.21 to be used
Keep development dependencies up-to-date.
I updated the bundle.
- Dependency update

Allow simplecov 0.21 to be used

---

.github/workflows/ruby.yml
Rakefile
aruba.gemspec

Some improvements to the linting tasks
- Move `license_finder` out of the bundle and lint tasks and install it separately in CI
Additionally:
- Simplify rubocop and yard:junk task definitions
- Provide kramdown dependency so yard:junk doesn't error out
License finder has a lot of dependencies but is slow to update them. We also don't need to depend on any particular version.
I rank the lint task with the new definition.

Improve linting tasks

---

.github/workflows/ruby.yml
features/03_testing_frameworks/cucumber/steps/command/check_for_exit_statuses.feature
features/03_testing_frameworks/cucumber/steps/command/stop_command.feature
features/04_aruba_api/command/read_stdout_of_command.feature
features/04_aruba_api/command/run_simple.feature

Just one more step on the road to consistently green tests
This does two things:
- Make all MacOS jobs always finish to help with problem-solving when cukes fail there.
- Give several scenarios a bit more time to finish
In the end, we want to be certain that the tests will be green if nothing is broken. Right now, the MacOS builds fail far too often.
I ran the scenario, but it already was fine when run locally.

Improve test robustness a bit more

---

lib/aruba/processes/spawn_process.rb

Remove obsolete Ruby version check
Removes a check for Ruby version 1.9. Older versions are not supported and guarded against in the gemspec, so this check is no longer needed.
Clean things up.
CI.

Remove obsolete Ruby version check

---

CHANGELOG.md
aruba.gemspec

This allows us to test / release new versions of Cucumber without first having to come here to make a new release of Arubua.
I think the only reason to cap the max version would be if we knew there was a backwards-compatibility problem with a release of Cucumber, but there isn't, so I think we can safely just remove it?

Allow newer versions of Cucumber

---

aruba.gemspec

Loosen dependency on the contracts gem to allow version 0.17.
Keep things up-to-date. We still allow 0.16 because 0.17 requires Ruby 3.0.
CI will check it.

Loosen dependency on the contracts gem

---

features/README.md

This is a start of "get the default branch name" used everywhere.
A name change was started, this keeps it going.
It was mentioned in https://github.com/cucumber/common/issues/1507?#issuecomment-841312710
Not tested yet!
I searched, and found more places than this, but this is a start.

README: Renamed default branch

---

.github/workflows/ruby.yml
CHANGELOG.md
CONTRIBUTING.md
README.md
features/README.md

Update remaining references of `master` branch to `main`
- Update references to `master` branch to main in documentation
- Make GitHub Actions run when targeting `main`
The default branch was renamed but that made the documentation and GitHub Actions configuration incorrect. This fixes that.
N/A
- Documentation update

Update remaining references to default branch

---

spec/spec_helper.rb

Remove Bundler.require from `spec/spec_helper.rb`.
Our code should require necessary dependencies explicitly. This also avoids circular reference errors while loading specs
Ran the specs.

Remove Bundler.require_relative from spec helper

---

aruba.gemspec
lib/aruba/api/bundler.rb

Bundler is a runtime dependency inside `aruba/api/bundler` - So require it as so
Fix gemspec to pull in bundler as a requirement of using the gem (As it's needed to run some methods)
Self-explanatory
When running cucumber-rails in a test/valid context, this throws an error when consuming aruba helpers
CI / Manual

bugfix: Undefined module/class `Bundler` when running cucumber-rails from RubyMine

---

features/03_testing_frameworks/cucumber/steps/command/stop_command.feature
features/04_aruba_api/command/run_command.feature
features/04_aruba_api/command/send_signal_to_command.feature
features/04_aruba_api/command/stop_single_command.feature

Fix some cucumber timeout issues on MacOS in CI
Makes some timeouts larger to avoid cucumber scenario failures.
Cukes fail regularly in CI on MacOS.
CI of course.

Fix some cucumber timeout issues on MacOS in CI

---

spec/aruba/matchers/file_spec.rb

Fix specs for have_file_content matcher
- Give file under test known contents instead of assuming it does not
exist
- Update expected failure messages
This avoids a rare test failure that seems to happen if the file under
test accidentally exists.
I ran the specs.

Fix specs for have_file_content matcher

---

.github/workflows/ruby.yml
.rubocop.yml
README.md
aruba.gemspec
features/step_definitions/hooks.rb
lib/aruba/cucumber/command.rb
lib/aruba/platforms/windows_environment_variables.rb

Drop support for Ruby 2.4
- Bump required ruby version to 2.5
- Adjust GitHub Actions configuration accordingly
- Bump TargetRubyVersion in RuboCop configuration and autocorrect new offenses
Fixes #728.
CI.
- Potentially breaking change
- Update of dependencies
- My change requires a change to the documentation.
- I have updated the documentation accordingly.

Drop support for Ruby 2.4

---

spec/aruba/command_spec.rb

Make tests for Aruba::Command a bit clearer
Move stuff out of the before step so it's clearer what's being tested.
Spec clarity.
Ran specs.

Make Aruba::Command specs clearer

---

lib/aruba/platforms/unix_platform.rb
lib/aruba/platforms/windows_platform.rb
spec/aruba/api/commands_spec.rb
spec/aruba/processes/spawn_process_spec.rb

Use Ruby's built-in windows platform detection.
Use `Gem.win_platform?` instead of piggy-backing on Cucumber to check if we're running on Windows.
This avoids the need to load Cucumber when using Aruba with RSpec. A step toward fixing #402 and #806.
Mostly CI.

Use Ruby's built-in windows platform detection

---

features/04_aruba_api/core/expand_path.feature
lib/aruba/api/core.rb
spec/aruba/api/core_spec.rb
spec/aruba/matchers/command_spec.rb

Make it easier to locate where an absolute file name was passed to Aruba by raising an error about it.
Instead of a warning, raise an error.
Fixes #691.
Specs and scenarios have been updated. I also tried this with the simplecov features.
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation update
- My change requires a change to the documentation.
- I have updated the documentation accordingly.

Make absolute file name warning an error

---

Manifest.txt
lib/aruba/cucumber.rb
lib/aruba/cucumber/command.rb
lib/aruba/cucumber/parameter_types.rb

Update some step definitions to use Cucumber Expression syntax
This updates some of the step definitions in the command section to use Cucumber Expression syntax. In particalar, this uses the {string} parameter type for the expected output strings.
The main goal of this change is to allow specifying expected output that contains double qoutes.
I ran some of the cucumber scenarios that seemed relevant. 

Update some step definitions to use Cucumber Expression syntax

---

features/03_testing_frameworks/cucumber/steps/filesystem/append_to_file.feature
lib/aruba/api/filesystem.rb

Remove deprecated functionality from `#append_to_file`
Removes the feature where appending to a non-existing file would create the file.
This functionality was deprecated and is now removed in preparation for the 2.0 release. Fixes #726.
I ran the relevant cucumber feature file.

Remove ability to append to non-existent file

---

lib/aruba/console.rb
lib/aruba/cucumber/command.rb
lib/aruba/matchers/command/have_exit_status.rb
lib/aruba/platforms/command_monitor.rb
lib/aruba/processes/basic_process.rb

- Don't pretend console self is nil
- Use #empty? instead of #nil? to distinguish empty commands
- Simplify implementation of have_exit_status matcher
Remove methods that make non-nil objects pretend they are nil.
Removes implementations of `#nil?` that returned `true` for classes that are not NilClass; Also updates the `#inspect` method for `self` in the Aruba console not to return the string `"nil"`.
Having objects respond with `true` to the `#nil?` message is super-confusing for humans, machines and cyborgs.
I ran the specs and cukes.

Remove pretend-nils

---

features/05_use_rspec_matchers/file/be_existing_executable.feature
spec/aruba/matchers/file_spec.rb

Improve testing of `be_an_existing_executable` matcher
* Test behavior of `be_an_existing_executable` matcher in the specs
* Leave simple scenario as documentation
* Provide separate scenarios for Windows and Unix
Continuous improvement.
I ran the relevant specs and scenarios.
- Documentation update
N/A

Improve testing of be_an_existing_executable matcher

---

.rubocop.yml

Simplify RubyCop config by inheriting default exclusions
RubyCop excludes tmp/ and vendor/ by default, so remove them from the local exclusions list and make sure they remain even if we add new local exclusions, by specifying the 'merge' inherit mode for exclusions.
Simpler is better.
N/A

Inherit default RuboCop exclusions

---

.github/workflows/ruby.yml
.simplecov
features/support/simplecov_setup.rb
spec/spec_helper.rb

Test with Ruby 3.1 in CI
Add Ruby 3.1 to the CI matrix; also add `--disable-did-you-mean` option to avoid extra output that disturbs the cucumber scenario's.
Aruba should work with Ruby 3.1.
CI

Test with Ruby 3.1 in CI

---

features/03_testing_frameworks/cucumber/steps/command/wait_for_output_of_command.feature
lib/aruba/cucumber/command.rb

Fix the 'wait for output to contain' steps
- Fix implementation of steps for waiting for output
- Add scenario to test the 'stop the command if output contains' step
Fixes #854.
Three new scenarios test this functionality.

Fix steps that wait for output from commands

---

CONTRIBUTING.md
Gemfile
aruba.gemspec
gemfiles/cucumber_4.gemfile
gemfiles/cucumber_5.gemfile
gemfiles/cucumber_6.gemfile
gemfiles/cucumber_7.gemfile

Remove pry-byebug and byebug.
This removes the hard development dependencies on byebug and pry-byebug. This will allow intalling the latest version of pry. If pry-byebug is needed, it can still be added in Gemfile.local. The pry dependency is set to be lenient enough to allow installing a version compatible with pry-byebug.
This keeps dependencies up-to-date. I find I don't use byebug so dropping it from the default set shouldn't be problematic. Once support for Ruby 2.5 has been dropped, the new debug gem can be added as a permanent dependency to provide extended debugging features by default.
CI

Remove pry-byebug depedency

---

lib/aruba/platforms/unix_platform.rb
spec/aruba/platforms/unix_platform_spec.rb
spec/aruba/platforms/windows_platform_spec.rb

Ensure `Gem.win_platform?` is available by explicitly requiring `rubygems`.
Even though rubygems is nearly always loaded by ruby automatically, it is possible to avoid doing so. Therefore, to make platform detection work, we have to require "rubygems" explicitly.
Fixes #852.
Specs were added that exercise the relevant functionality for the case where rubygems is not loaded.

Ensure Gem.win_platform? is available

---

.rubocop.yml
aruba.gemspec
spec/aruba/api_spec.rb
spec/aruba/command_spec.rb

Handle new offenses found by the latest versions of rubocop and rubocop-rspec.
- Bump rubocop dependency to ensure Style/FetchEnvVar is present
- Disable Style/FetchEnvVar
- Autocorrect RSpec/VerifiedDoubleReference
Keeping the build green.
I ran RuboCop.

Fix new RuboCop offenses

---

.github/workflows/ruby.yml

Test with JRuby 9.3 in CI
Adds JRuby 9.3 with Cucumber 7 to the CI build matrix
We will soon drop support for Ruby 2.5, and with it JRuby 9.2. It's good to make sure Aruba will keep working with the most recent JRuby version.
I'll need to check the correct GitHub Action is run.

Test with JRuby 9.3 in CI

---

features/support/env.rb

Removes obsolete support for Cucumber 3 from `features/support/env.rb`.
With Cucumber 4, `scenario.feature` stopped working in a `Before do |scenario|` block. Since Aruba no longer supports Cucumber below version 4, the code path for using `scenario.feature` was obsolete and has now been removed.
Additionally, the parameter for a `Before` block is no longer a scenario. Instead, it's a test case. I've adjusted the parameter name accordingly. More details here: https://github.com/cucumber/cucumber-ruby/issues/1432.
I came across https://github.com/cucumber/cucumber-ruby/issues/1432 and decided to clean things up.
I ran one cucumber feature file.

Remove code supporting cucumber 3 from simplecov set-up

---

spec/aruba/platforms/command_monitor_spec.rb

This improves specs for Aruba::CommandMonitor, fixing a lint failure.
- Improve spec description
- Add spec for failure mode
Fixes #877.
I ran the updated spec and rubocop.

Improve specs for Aruba::CommandMonitor

---

.github/workflows/ruby.yml
.rubocop.yml
README.md
aruba.gemspec
fixtures/cli-app/cli-app.gemspec
fixtures/empty-app/cli-app.gemspec
lib/aruba/api/core.rb
lib/aruba/event_bus/name_resolver.rb
lib/aruba/processes/basic_process.rb

Drop support for Ruby 2.5
- Require Ruby 2.6 or higher in the gemspec
- Update RuboCop configuration and fix new offenses
- Update set of Rubies in CI
With the release of JRuby 9.3.0.0, we can drop compatibility with Ruby 2.5. MRI 2.5 has been unmaintained for a while now.
CI
This is a potentially breaking change for versions of rubygems and bundler that do not take ruby version requirements into account. From the standpoint of semver, it is not a breaking API change so does not require a major version bump.

Drop support for Ruby 2.5

---

fixtures/cli-app/lib/cli/app.rb
fixtures/cli-app/spec/spec_helper.rb
spec/aruba/event_bus/name_resolver_spec.rb
spec/spec_helper.rb

Fixes Style/RedundantConstantBase offenses. This cop was introduced in RuboCop 1.40.0.
Autocorrects Style/RedundantConstantBase, and cleans up specs that turned out to be actually the same.
Make the build pass again.

Correct Style/RedundantConstantBase offenses

---

.github/workflows/ruby.yml
README.md

Add support for JRuby 9.4
This just adds jruby-9.4 to the build matrix for now.
JRuby 9.4 is out and we should support it officially.
CI.

Add support for JRuby 9.4

---

.github/workflows/ruby.yml
README.md

Add Ruby 3.2 to the build matrix
Adds Ruby 3.2 to the build matrix on Linux and MacOS. Leaves Windows as-is since we already had problems with 3.1 there. Also, updates the Ruby version RuboCop runs under.
It's Christmas.
I ran rake locally on Ruby 3.2
- New feature (non-breaking change which adds functionality)

Support CRuby 3.2

---

features/support/timing.rb

Refactor the helper that shows the slowest 20 Cucumber scenario's after a run
- Refactor slowest scenario list display
- Remove code supporting Cucumber < 4 from scenario timing helper
RuboCop registered an offense for this code but I saw some more opportunity for improvement
I ran cucumber and checked that the slowest scenarios were displayed

Improve Cucumber timing helper

---

Dockerfile

Remove obsolete Ruby version statement in the Dockerfile comments
This change removes the now-incorrect statement that the Dockerfile will use the lowest supported Ruby version.
There is no real need to use the lowest version since this Dockerfile is provided just so contributors can use a known-good development setup if necessary.
Renovate updated the Ruby version, making the comment incorrect.
N/A

Remove obsolete statement about Ruby version used in Dockerfile

---

lib/aruba/processes/spawn_process.rb

Depend on process launcher to set child process environment
This change removes a needless `#with_environment` call when spawning a process. Setting the local environment at this point no effect since we already set the environment by configuring the child process launcher.
Cleaning up a needless complication in preparation for switching to `Process.spawn`.
Specs and cukes were run and there was no regression.

Depend on process launcher to set child process environment

---

features/05_use_rspec_matchers/file/be_a_command_found_in_path.feature
lib/aruba/matchers/file/be_a_command_found_in_path.rb
spec/aruba/matchers/file_spec.rb

Improve `be_a_command_found_in_path` matcher and its tests
* Test all behavior in the specs
* Leave simple scenario as documentation
* Simplify implementation
* Render correct path in failure message
This was extracted from #799.
Specs were added.

Improve be_a_command_found_in_path matcher and its tests

---

Appraisals
aruba.gemspec
gemfiles/cucumber_4.gemfile
gemfiles/cucumber_5.gemfile
gemfiles/cucumber_6.gemfile
gemfiles/cucumber_7.gemfile
gemfiles/cucumber_8.gemfile
lib/aruba/cucumber/command.rb
lib/aruba/platforms/unix_platform.rb
lib/aruba/platforms/windows_command_string.rb
lib/aruba/platforms/windows_platform.rb
lib/aruba/processes/spawn_process.rb
spec/aruba/platforms/windows_command_string_spec.rb
spec/aruba/processes/spawn_process_spec.rb

This replaces ChildProcess with Process.spawn for the purpose of starting, stopping and controlling the processes under test.
To make this change be the least invasive, I created a new class that emulates the interface provided by ChildProcess, with a few differences where this was more practical. For example, where ChildProcess provides an #io method that returns an object giving access to stdout etc., this new class simply privides #stdout and related methods directly.
This also removes the childprocess dependency.
This fixes #884.
I ran the full test suite with MRI 3.2 and JRuby 9.4.
I also added specs for SpawnProcess so its tested more fully in the RSpec suite.
- Internal change (refactoring, test improvements, developer experience …

Replace ChildProcess with Process.spawn

---

Rakefile
aruba.gemspec

Removes dependencies that pull in yard and hence webrick
By removing yard-junk and pry-doc, we drop the dependency on YARD. This is done mainly to avoid the outdated dependency on webrick that YARD pulls in in turn.
Running yard-junk was not part of CI, so we lose nothing there. When desired, yard junk can be checked for by running `yard doc --plugin junk`.  Documentation provided by pry-doc can easily be read outside of the REPL.
Dropping an outdated dependency.
N/A

Remove yard-junk and pry-doc dependencies

---

spec/aruba/event_bus_spec.rb

Replace `match_array` with just `eq`.
Both elements of the array are the same, so testing for equality is just fine.
This fixes a RuboCop RSpec/MatchArray offense.
I ran the relevant spec file.

Simplify use of match_array to just eq

---

.rubocop.yml

Just updating the RuboCop configuration to match the current setup.

Require development dependencies to be in the gemspec

---

features/03_testing_frameworks/cucumber/disable_bundler.feature

Make the 'disable bundler' scenarios work with Bundler version 2.4.17 and up
In recent versions of bundler, plain 'bundle' no longer prints a message for dependencies that were not updated. This change makes the scenarios use 'bundle list' instead, which should always keep printing all dependencies.
The relevent cucumber scenario started failing
I ran the scenario again after the update to the code.
N/A

Update 'disable bundler' scenarios to work with Bundler 2.4.17 and up

---

.github/workflows/ruby.yml
.rubocop.yml
README.md
aruba.gemspec
fixtures/cli-app/cli-app.gemspec
fixtures/empty-app/cli-app.gemspec

Drop support for Ruby 2.6
Bumps up the mimimum Ruby version and adjusts rubocop configuration and GitHub Actions accordingly.
Ruby 2.6 has been unmaintained for a long time.
N/A

Drop support for Ruby 2.6

---

lib/aruba/api/commands.rb
spec/aruba/api/commands_spec.rb

Some codebases follow the convention of enforcing frozen string literals, e.g. by using a `# frozen_string_literal: true` magic comment or via `RUBYOPT`.
The current implementation of the `type` API Command breaks when this is the case, as it mutates the string passed to it to add a newline.
To avoid this, this PR tweaks the implementation to use interpolation rather than mutating the string input value.
Allows the `type` API Command to be used in codebases that enforce frozen string literals.
I've added a test case to the existing specs for `Aruba::Api::Commands#run_command` to assert that frozen strings can be passed as an input value.

Allow for type input of frozen strings

---

.github/workflows/ruby.yml

Use ruby-setup's native caching in CI instead of rolling our own.
The ruby/ruby-setup action supports caching with different gemfiles out of the box. This removes the custom caching setup and turns on caching in the ruby-setup configuration instead.
See https://github.com/ruby/setup-ruby#matrix-of-gemfiles.
Removes a needless complication.
CI.

Use ruby-setup's native caching

---

lib/aruba/basic_configuration.rb
lib/aruba/command.rb

Fixes two new RuboCop offenses
- Autocorrect Lint/SymbolConversion
- Correct Style/SuperWithArgsParentheses offense
The latest RuboCop has some new cops.
Ran RuboCop after.
N/A

Fix some new RuboCop offenses

---

lib/aruba/basic_configuration.rb
lib/aruba/cucumber/command.rb
spec/support/shared_contexts/aruba.rb

Fix new RuboCop offenses
The latest version of rubocop-performance introduces Performance/StringIdentifierArgument. This PR fixes resulting failures.
Stop builds for other PRs from failing in CI.
I ran RuboCop.
N/A

Fix new RuboCop offense

---

features/03_testing_frameworks/cucumber/steps/command/debug_your_command_in_aruba.feature

Clean up interactive debugging scenario. Also, allow it to run on JRuby.
- Remove stream configuration that is no longer needed
- Remove obsolete warning about binding.pry and related code
- Mark debugging scenario as supported on JRuby
While debugging #910, I noticed some obsolete bits in the scenario that is failing with upcoming Ruby 3.3.
I ran the scenario again after applying the simplifications. I also checked that it passed on JRuby.

Simplify scenario describing interactive debugging

---

.github/workflows/ruby.yml
features/03_testing_frameworks/cucumber/steps/command/debug_your_command_in_aruba.feature
features/03_testing_frameworks/cucumber/steps/command/wait_for_output_of_command.feature
lib/aruba/console.rb

Prepare for upcoming Ruby 3.3
This pull request consists of the following changes:
- Test with Ruby 3.3.0-preview3 in CI. This tests that Aruba is ready for Ruby 3.3
- Use irb instead of pry in the interactive debugging scenario. This fixes an issue in the Cucumber scenario's. This issue occurs because our output streams are not reall TTYs. See #910 for details.
-  Stop requiring 'irb/ext/save-history' extension in Aruba console. This extension has been renamed and did not do what its old name said.
- Ensure irb uses a consistent prompt format in tests on all Ruby versions.
Mainly, #910.
I ran the Cucumber scenario with the added gem in Ruby 3.3.0-preview3. I also tried just setting TERM=dumb as in https://github.com/rails/rails/pull/48369 but that didn't work.
- Internal change …

Prepare for Ruby 3.3

---

.github/workflows/ruby.yml

Extends the GitHub Actions jobs to run the specs on Windows on all supported Rubies
This is a follow-up for https://github.com/cucumber/aruba/pull/892.
Since ChildProcess is no longer used, running the specs on Ruby 3.1 and 3.2 should work.
Closes #871.
CI

Update GitHub Actions to run specs on Windows on all supported Rubies

---

.github/workflows/ruby.yml
.rubocop.yml
aruba.gemspec
fixtures/cli-app/cli-app.gemspec
fixtures/cli-app/lib/cli/app.rb
fixtures/cli-app/spec/spec_helper.rb
fixtures/empty-app/cli-app.gemspec
lib/aruba/platforms/unix_environment_variables.rb
lib/aruba/platforms/unix_platform.rb
spec/spec_helper.rb

Drop support for Ruby 2.7
- Drop support for Ruby 2.7
- Build with Rubies 3.0 through 3.3 in CI
- Autocorrect Style/ArgumentsForwarding
- Autocorrect Lint/RedundantDirGlobSort
Ruby 2.7 has been EOL for quite some time now
N/A

Support Ruby 3.0 and up

---

features/01_getting_started_with_aruba/supported_testing_frameworks.feature
features/06_use_aruba_cli/initialize_project_with_aruba.feature
lib/aruba/initializer.rb

Make minitest scenarios run at least one test so test summary is displayed.
This change fixes the name of the test method in the minitest scenario so minitest actually recognizes it as a test. It also updates the setup code which was outdated. This was never noticed because it was not run.
It also updates the minitest initializer so it generates a dummy test, and fixes the test setup that it generates.
Due to how test success is checked, the failure to run at least one test was never noticed. A change in behavior in minitest exposed the problem by making nearly all CI jobs fail. See https://github.com/minitest/minitest/pull/986.
The failing scenarios now pass.

Fix minitest setup code and make minitest support scenarios run at least one test

---

spec/aruba/matchers/command/have_output_size_spec.rb
spec/aruba/matchers/command_spec.rb
spec/aruba/matchers/path_spec.rb

Removes some unused spec helper methods.
Specs contained helper methdos that were defined but never used. This change removes them.
Originally part of #881, but since that change turned out to be a bit more complex than expected, I'm presenting it separately here.
I ran the specs.

Remove superfluous method definitions from specs

---

lib/aruba/cucumber/command.rb
lib/aruba/matchers/command/have_output_size.rb
spec/aruba/matchers/command/have_output_size_spec.rb

Make `#have_output_size` matcher work with process objects, and deprecate its use with strings.
- Simplify existing specs for `#have_output_size matcher`
- Make `#have_output_size` matcher work with process objects
- Deprecate use of `#have_output_size1 matcher with a string actual
- Use `#have_output_size` matcher with process object in supplied step
Fixes #484.
I ran the relevant specs and cukes.

Make #have_output_size work on a process

---

lib/aruba/api/core.rb
lib/aruba/platforms/local_environment.rb
lib/aruba/platforms/unix_platform.rb
lib/aruba/processes/debug_process.rb
lib/aruba/processes/in_process.rb

Cleans up code related to environment manipulation.
This does two things:
- It avoids having two methods `#with_environment` that, apart from operating at a different level, also use their arguments differently: one takes changes to the environment as an argument, the other takes a full replacement environment.
- It decouples LocalEnvironment from the global platform singleton. This is neater because it makes the dependency go only one way.
I just spent quite some time looking at the wrong `#with_environment` and wondering how any environment variables could be left inside the block.
CI will test it.

Improve clarity of environment manipulation

---

aruba.gemspec

Update rubocop-rspec to version 3.0
Needs updating and Renovate doesn't seem to be doing it for us :disappointed:
I ran `bundle exec rubocop`

Update rubocop-rspec to version 3.0

---

aruba.gemspec

Using add_runtime_dependency is soft-deprecated and now flagged by RuboCop.

Replace soft-deprecated runtime dependency specification

---

CONTRIBUTING.md
aruba.gemspec
fixtures/cli-app/script/console
spec/support/configs/pry.rb

Remove pry dependency since irb is now good enough
Removes pry dependency and other related bits.
I don't really use pry anymore since irb is good enough now.
CI
- Documentation update
- My change requires a change to the documentation.
- I have updated the documentation accordingly.

Remove dependency on pry

---

features/03_testing_frameworks/cucumber/steps/command/run_commands_which_require_a_shell.feature
features/step_definitions/hooks.rb
lib/aruba/cucumber/command.rb
lib/aruba/cucumber/parameter_types.rb

Introduce Cucumber parameter type 'command' and use it
This introduces a new Cucumber parameter type 'command', matching a string between backticks. It then uses this new parameter types to replace the old regular expression based step definitions. This allows more steps to use the Cucumber Expression syntax.
It also removes the need for python to be installed on of the scenarios that uses these step definitions, to ensure they're properly tested.
While working on #894, I noticed that the steps matching output from a particular command could not match against a command including quote characters. This change will make it easier to add an extra step definition to support that case. **Update:** It turns out matching is possible by using `\`. The present change is still an improvement, …

Introduce Cucumber parameter type 'command'

---

features/03_testing_frameworks/cucumber/steps/command/check_output_of_command.feature
features/03_testing_frameworks/cucumber/steps/command/check_stderr_of_command.feature
lib/aruba/cucumber/command.rb

Improve step failure messages for two provided cucumber steps. Also, fix logic of one of the steps so it does what the wording says it does.
- Fix logic of cucumber step '<channel> should not contain anything', requiring all commands to have no output on the channel, not just one.
- Improve the failure message of the same step so that it shows the actual output.
- Fix cucumber step 'it should pass/fail with exactly:' so that the failure message of the output comparison shows the correct diff.
This fixes #942.
I added cucumber scenarios testing the failure case for both steps, and after implementing the fix I ran the whole test suite to verify that I didn't break anything.

Improve two step failure messages

---

aruba.gemspec
features/03_testing_frameworks/cucumber/steps/command/check_output_of_command.feature
features/03_testing_frameworks/cucumber/steps/command/check_stderr_of_command.feature

Fix the build by the bumping diff-lcs dependency and updating expected output.
Version 1.6.0 of diff-lcs included a bug fix that corrects the hunk ranges it outputs. This change bumps the minimum version of diff-lcs to 1.6.0 so this change is sure to be included, and updates the expectations in the cucumber scenarios that depend on exact diff-lcs output.
Builds were failing.
I ran the previously failing scenarios.
N/A

Update expected diff output to match changes in diff-lcs

---

.github/workflows/test.yml

Add Ruby 3.4 to the test matrix
Adds 3.4 to the list of versions of Ruby to be used for testing with GitHub Actions. This version of Ruby is only combined with Cucumber 9, since only Cucumber 9.2.1 (and up) will work with Ruby 3.4. 
Ruby 3.4 is out. We should verify that Aruba works with it.
I ran the test suite with 3.4 locally. With the release of Cucumber 9.4.1, the suite passes.
N/A

Add Ruby 3.4 to the test matrix

---

aruba.gemspec

In https://github.com/cucumber/aruba/pull/956, the upper bound of these dependencies was relaxed. However, the lower bound was made exclusive. This change restores the lower bound.

Restore lowest allowed rspec and rspec-expectations versions
