cucumber/aruba

- lib/aruba/matchers/file.rb
@mattwynne 
Fix for diffable + A Fix for the failure message of the new file size matcher...
> Diffable content

- lib/aruba/platforms/unix_command_string.rb
- lib/aruba/platforms/unix_platform.rb
- lib/aruba/platforms/windows_command_string.rb
- lib/aruba/platforms/windows_platform.rb
- lib/aruba/processes/spawn_process.rb
> Support for WindowsProcess added

- History.md
- cucumber.yml
- features/api/text/extract_text.feature
- features/api/text/sanitize_text.feature
- features/api/text/unescape_text.feature
- features/commands/output/all_output.feature
- features/output.feature
- features/step_definitions/aruba_dev_steps.rb
- features/step_definitions/hooks.rb
- lib/aruba/api.rb
- lib/aruba/api/command.rb
- lib/aruba/api/deprecated.rb
- lib/aruba/api/text.rb
- lib/aruba/cucumber/command.rb
- lib/aruba/cucumber/file.rb
- lib/aruba/cucumber/hooks.rb
- lib/aruba/matchers/command/have_output.rb
- lib/aruba/matchers/command/have_output_on_stderr.rb
- lib/aruba/matchers/command/have_output_on_stdout.rb
- lib/aruba/matchers/string.rb
- lib/aruba/matchers/string/include_output_string.rb
- lib/aruba/matchers/string/match_output_string.rb
- lib/aruba/matchers/string/output_string_eq.rb
- lib/aruba/platforms/unix_platform.rb
This PR should make it easier for users to write their own steps. I created this PR because some valuable feedback in rspec/rspec-expectations#840. This should also help with  #227.
> Add some new matchers to make it easier to write steps for cucumber

- README.md
Fix README links for CONTRIBUTING.md and LICENSE files. Fixed #328 .
> Fix README links for CONTRIBUTING.md and LICENSE files. [skip ci]

- aruba.gemspec
Upgraded bundler to '~> 1.11.0'
Here is my Travis builds: https://travis-ci.org/jasnow/aruba/builds/97728738
> Upgraded bundler to '~> 1.11.0'

- aruba.gemspec
I fixed
`gem 'cucumber', ~> '1.3.20'`
to
`gem 'cucumber', '~> 1.3.20'`
> Fix the post install message

- History.md
- aruba.gemspec
- features/matchers/file/be_a_command_found_in_path.feature
- features/matchers/file/be_existing_executable.feature
- lib/aruba/matchers/file/be_a_command_found_in_path.rb
Just to test the code against all supported rubies.
> Added a matcher to check if a file a command found in PATH

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- README.md
Add vision to show why we do things in the aruba project.
This PR adds our vision to explain why we work on aruba. To explain why we add features and why implement them in the given way.
This should make it easier for new cucumber's to understand our motiviation. I added this after a discussion with a user. Please also see this issue https://github.com/cucumber/aruba/issues/361.
No, this IS the test. If this doesn't work, we can remove it from the readme.
> Add vision to the project readme and clean up CONTRIBUTIONS.md

- README.md
This PR re-organizes the README to make it easier for user to see that there are different versions of documentation.
> Better hint for readme version

- features/rspec/integration.feature
> Fixes a typo for rspec feature test.

- doc/dependency_decisions.yml
- features/matchers/path/have_permissions.feature
- spec/aruba/api_spec.rb
Fix issue #388
This PR changes the permissions to values which are supported by Windows and Linux.
With the current test suite.
> Set permissions to values which are supported on Windows

- README.md
> chore(readme): Remove repetition in rspec section

- features/getting_started/writing_good_feature_tests.feature
> Fix typo in documentation

- features/development/run-test-suite.feature
> Fix spelling in documentation

- README.md
Image related to the build status were not rendered properly. This PR fixes the problem by removing HTML for the table and using native markdown syntax. I had to remove the "colspan" in favour of a header. 
You can see the new README in this PR.
> Fix build status table in README

- aruba.gemspec
Aruba install for development was failed on Ruby 2.4.0.
After updating runtime dependency of cucumber, unit tests are still failed.
However I would like to share the situation.
```
$ ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
$ bundle -v
Bundler version 1.14.3
$ bundle install --path vendor/bundle
...
Resolving dependencies...
Bundler could not find compatible versions for gem "gherkin":
In Gemfile:
gherkin (~> 4.0)
gherkin (~> 4.0)
aruba was resolved to 0.14.1, which depends on
cucumber (~> 2.3.0) was resolved to 2.3.0, which depends on
gherkin (~> 3.2.0)
...
```
After updating `aruba.gemspec`, and installing again.
rspec tests were succeeded.
```
$ bundle exec rake test:rspec
356 examples, 0 failures
```
cucumber tests were failed.
```
$ bundle exec rake …
```
> Fix dependency error for install

- Gemfile
- Rakefile
- aruba.gemspec
- doc/dependency_decisions.yml
- lib/aruba/api/command.rb
- lib/aruba/generators/script_file.rb
- lib/aruba/platforms/windows_command_string.rb
- lib/aruba/tasks/docker_helpers.rb
- spec/aruba/api_spec.rb
- spec/aruba/matchers/command_spec.rb
> Fix complaints of rubocop

- README.md
- features/README.md
This PR tries to improve the README.
> Improve README me to make it easier to get started with "Aruba" for beginners

- Rakefile
- I am trying to make the Travis build run license_finder
> Rakefile: wrap in bundle exec

- README.md
This PR collects tiny copy-edits to the README document.
- a longer, more descriptive link to the Released version's README
- spellings
- typo
- capitalizations
- hyphenations
I made a comment in #444, and Max kindly asked me to make a PR out of them.
Polishing the README is helping new-comers since what they see first _can_ be that document.
> README: Copy-edits

- .travis.yml
This updates the ruby versions for Travis CI.
> Update ruby versions in Travis-CI

- lib/aruba/matchers/string/include_output_string.rb
- lib/aruba/matchers/string/match_output_string.rb
- lib/aruba/matchers/string/output_string_eq.rb
> Fix UTF-8 issues with jRuby

- CHANGELOG.md
Lots of changes in accordance with [cucumber/cucumber 251](https://github.com/cucumber/cucumber/issues/251)
Working to normalize documents across the various repos.
> CHANGELOG update for cucumber/cucumber #251

- features/README.md
This PR fixes the URL to our gettting started repository
We move the "getting started" repository to the cucumber organisation.
> Fix link to getting started repository

- README.md
Add @mvz to aruba's core team.
Welcome @mvz to aruba's core team. This PR changes the documentation accordingly. @aslakhellesoy Would you mind to add @mvz to the core member list of aruba?
Due to his ongoing effort and the way he works, I think @mvz is a valueable addition to aruba's core team.
> Add @mvz to aruba's core team

- History.md
- lib/aruba/version.rb
Prepare release 0.14.3
Update History and version number
Let's have a released version with up-to-date dependencies.
- Version bump
- Update documentation
- My change requires a change to the documentation.
- I have updated the documentation accordingly.
> Prepare release 0.14.3

- README.md
The "Code Branches" section of the readme file was a little confusing, so I've tidied it up a little.
> README: add quotes to improve readability

- README.md
Remove me from the list of maintainers as I don't have time to support aruba in way it deserves. There's @mvz now who is a good maintainer and helps the project to make progress.
I struggle to support aruba and it's community in a "proper" way. I'm not allowed to do open source during business hours and don't have enough time for aruba in my spare time. I hope this might change in the future.
> Remove maxmeyer from list of maintainers

- Gemfile
Updates development dependencies
Updates dependencies to use the latest versions on modern Rubies, as far as possible. RuboCop is not updated because 0.50.0 is the last versions supporting all Ruby versions that Aruba supports.
It's good to stay up-to-date.
> Update development dependencies

- CHANGELOG.md
- lib/aruba/version.rb
Hi @mvz I cut a checkpoint roughly halfway between 1.0.alpha2 and the current master. And I've badged it as a 1.0.alpha.3
Hopefully this gives us "some" of the newer code in a release so we can see how much of the newer stuff is working / not working.
Obviously the majority of stuff between 1.0.alpha2 and master is mainly test/dev tweaks, so I don't envision this will be "that" different too the 2nd alpha, but it includes a healthy amount of commits (Around 150-200).
Hopefully getting this cut and released will make the job of releasing a 4th alpha / stable 1.0 a bit easier, as we can see what stuff here works and what doesn't.
> Release 1.0.0.alpha3

- CONTRIBUTING.md
Just a tiny documentation fix.
> GitHub is not Github

- lib/aruba/colorizer.rb
- lib/aruba/platforms/announcer.rb
> Replace problematic AnsiColor module with simple implementation

- .travis.yml
Improve Travis config to avoid build failures.
* Ensure trusty distribution is used so no Java errors occur
Builds failing on master
> Fix JRuby builds on Travis

- aruba.gemspec
Use childprocess 3
Updates dependency to `~> 3.0`, the latest release of childprocess.
Staying up-to-date.
Travis.
> Bump childprocess dependency

- Gemfile
- Rakefile
- aruba.gemspec
Broaden the range of allowed versions of Thor.
Thor 1.0 is out and our users should be allowed to update to it.
Tests ran.
> Allow thor 1.0 to be used

- aruba.gemspec
- features/support/env.rb
- features/support/timing.rb
Support latest Cucumber.
Loosen dependency on Cucumber; Fix some helpers used in Aruba's features.
Fixes #714.
I ran the cucumber features.
> Support Cucumber 2.4 through 4.x

- features/05_use_rspec_matchers/file/be_a_command_found_in_path.feature
- features/05_use_rspec_matchers/file/be_existing_executable.feature
- lib/aruba/api/core.rb
- lib/aruba/api/filesystem.rb
- lib/aruba/cucumber/file.rb
- lib/aruba/platforms/simple_table.rb
- spec/aruba/matchers/directory_spec.rb
- spec/aruba/matchers/file_spec.rb
- spec/support/shared_contexts/aruba.rb
Some small improvements collected over time.
See commit messages.
These are improvements I happened upon while working on other stuff that didn't fit in there. Nothing major.
I ran `bundle exec rake`
> Various code cleanups

- .rubocop.yml
- aruba.gemspec
- fixtures/cli-app/cli-app.gemspec
- fixtures/cli-app/spec/spec_helper.rb
- fixtures/empty-app/cli-app.gemspec
- spec/spec_helper.rb
Hi,
Thanks for working on this! :heart: 
However, while maintaining this in Debian, we found that this library relies on `git` to list the files which could be done via pure Ruby alternative -- which is what this PR does.
As an addition, this PR makes sure that this gem only ships the required files to the end-users and not other things which are not needed by them! :rocket: 
Also, added `rubocop-packaging` as a `development_dependency` which will ensure the best practices.
Here's what it shows:
```
Inspecting 172 files
...C..........C.........C...........
....................................
....................................
....................................
............................
Offenses:
aruba.gemspec:48:16: C: Packaging/GemspecGit: Avoid using git to produce lists of …
```
> Drop `git ls-files` in gemspec

- .github/workflows/ruby.yml
- .travis.yml
- features/02_configure_aruba/basics.feature
Like on master, move to GitHub Actions on this old stable branch as well.
*Update:* Use GitHub Actions for newer Rubies, and TravisCI for the older ones.
- Update of development tooling
> Build 0-14-stable branch with GitHub Actions

- features/04_aruba_api/core/expand_path.feature
- features/04_aruba_api/filesystem/check_if_path_is_absolute.feature
- features/05_use_rspec_matchers/path/be_an_absolute_path.feature
Clean up some cucumber scenarios
- Improve scenario for Api#expand_path
- Improve wording of feature description
- Improve scenario naming
- Improve example rspec use inside feature files
- Improve scenario for be_an_absolute_path matcher
- Improve wording of feature description
- Remove edge case scenarios
- Improve scenario for #absolute?
The continuing quest to make the automatic tests more streamlined and most of all .. faster!
> Improve some cucumber scenarios

- .github/workflows/ruby.yml
Split tests step into two
This allows viewing time spent and logs of the specs before the cukes
have finished running.
- Developer experience improvement
> Split tests step into two

- Rakefile
- cucumber.yml
Simplify Cucumber configuration
- Specify parameters needed to run only work-in-progress scenarios into the Rakefile
- Remove old badly-maintained cucumber configuration file
The old `cucumber.yml` file contained a lot of stuff that was no longer useful. I took the opportunity to simplify the setup.
I ran cucumber and the `cucumber:wip` task.
> Clean up Cucumber configuration

- lib/aruba/contracts/is_power_of_two.rb
Fix Style/BitwisePredicate RuboCop offense
This is a small change that fixes a new RuboCop offense
This is a new RuboCop offense due to a new RuboCop version that makes unrelated pull requests fail.
I ran the specs.
N/A
> Fix Style/BitwisePredicate RuboCop offense
